
![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

1) Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.

In [510]:
import random
import numpy as np

 $\Delta m^2_{ij}=m^2_i-m^2_j$

In [511]:
exponent = random.randint(-9,-4) # Creacion de los m1, m2, m3 en base a el m1 aleatoria
m1 = 10**(exponent)
m2 = np.sqrt(7.39e-5+m1**2)
m3 = np.sqrt(2.449e-3+m2**2)

2) Choose random values for $\alpha_{ij}$ between $(0,2\pi)$

In [512]:
a12 = random.uniform(0,2*np.pi)
a13 = random.uniform(0,2*np.pi)
a23 = random.uniform(0,2*np.pi)

3 ) Obtain $\boldsymbol{Y}$

 $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

In [513]:
c12 = np.cos(a12)
c13 = np.cos(a13)
c23 = np.cos(a23)
s12 = np.sin(a12)
s13 = np.sin(a13)
s23 = np.sin(a23)

$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$

In [514]:
#Construccion de R
R = np.matrix([[c12*c13             , s12*c13            , s13],
              [-s12*c23-c12*s13*s23, c12*c23-s12*s13*s23, c13*s23],
              [s12*s23-c12*s13*c23 , -c12*s23-s12*s13*c23, c13*c23]])

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

In [515]:
# Construccion de D
D_m = np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)])

$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. 

In [503]:
# Valores utilizados para la creacion de U
t12 = np.deg2rad(33.82) # Asignacion de los thetas usando los valores de la grafica
t13 = np.deg2rad(8.61) 
t23 = np.deg2rad(48.3)
c_12 = np.cos(t12)
c_13 = np.cos(t13)
c_23 = np.cos(t23)
s_12 = np.sin(t12)
s_13 = np.sin(t13)
s_23 = np.sin(t23)

In [504]:
# Creacion de U
aux1 = np.matrix([[1, 0,  0],
                 [0,c_23,s_23],
                 [0,-s_23,c_23]])
aux2 = np.matrix([[c_13, 0,  s_13],
                 [0,    1,   0],
                 [-s_13, 0, c_13]])
aux3 = np.matrix([[c_12, s_12,  0],
                 [-s_12, c_12,  0],
                 [0,     0,  1]])
U = aux1 * aux2 * aux3
#Creacion de U transpuesta
U_transpose = U.transpose()

In [505]:
# Asignando los autovectores U1,U2,U3
U1 = np.c_[[c_12*c_13,-s_12*c_23-c_12*s_13*s_23,s_12*s_23-c_12*s_13*c_23]]
U2 = np.c_[[s_12*c_13,c_12*c_23-s_12*s_13*s_23,-c_12*s_23-s_12*s_13*c_23]]
U3 = np.c_[[s_13,c_13*s_23,c_13*c_23]]

$$ \boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}} $$

In [506]:
Y = R * D_m * U_transpose

4 ) Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors

$$ \boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y} $$

In [507]:
A = Y.transpose() @ Y 

In [508]:
# Comparacion de los valores de m1,m2,m3 con los obtenidos
Eigen = U_transpose @ A @ U
delta_m1 = Eigen[0,0]-m1
delta_m2 = Eigen[1,1]-m2
delta_m3 = Eigen[2,2]-m3
print("La diferencia para los valores teoricos con los obtenidos es para m1,m2 y m3 respectivamente:"
      ,delta_m1,delta_m2,delta_m3)

La diferencia para los valores teoricos con los obtenidos es para m1,m2 y m3 respectivamente: -7.936963413568811e-19 1.734723475976807e-18 1.3877787807814457e-17


In [509]:
Eigen_vectors = np.linalg.eig(A)[1]
print("El autovector correspondiente \n",np.c_[-Eigen_vectors[:,1]],
      "\n Con el vector  U1\n",U1)
print("\n")
print("El autovector correspondiente \n",np.c_[-Eigen_vectors[:,2]],
      "\n Con el vector  U2\n",U2)
print("\n")
print("El autovector correspondiente \n",np.c_[-Eigen_vectors[:,0]],
      "\n Con el vector  U3\n",U3)
# print(U1)
# print(U2)
# print(U3)

El autovector correspondiente 
 [[ 0.82142745]
 [-0.46312144]
 [ 0.33282949]] 
 Con el vector  U1
 [[ 0.82142745]
 [-0.46312144]
 [ 0.33282949]]


El autovector correspondiente 
 [[ 0.55031308]
 [ 0.49045305]
 [-0.67573021]] 
 Con el vector  U2
 [[ 0.55031308]
 [ 0.49045305]
 [-0.67573021]]


El autovector correspondiente 
 [[0.14970791]
 [0.73822377]
 [0.65773339]] 
 Con el vector  U3
 [[0.14970791]
 [0.73822377]
 [0.65773339]]


5) Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [516]:
# Comparacion entre los autovalores de A y los de Y
EY = np.linalg.eig(Y)[0]
Eigen_values_Y = np.array([EY[2],EY[1],EY[0]])
Eigen_valuesA = np.linalg.eig(A)[0]
print(r"La diferencia que se separa del cero numerico es debido a que los valores de m1,m2,m3 y thetas tienen cierta incertidumbre")
print(Eigen_values_Y -Eigen_valuesA**0.5)

La diferencia que se separa del cero numerico es debido a que los valores de m1,m2,m3 y thetas tienen cierta incertidumbre
[-0.22319317  0.04661083  0.05883772]


Como $$ \boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}} $$
$\boldsymbol{Y}$ es la multiplicacion de una matriz ortogonal generada por los angulos aleatorios, la raiz de los autovalores de A y una matriz ortogonal que diagonaliza A 

\begin{equation}
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}\\
\boldsymbol{A}=\boldsymbol{U} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{R}^{\operatorname{T}}\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}} \\
\boldsymbol{A}=\boldsymbol{U} (\boldsymbol{D}_{\sqrt{m}})^2 \boldsymbol{U}^{\operatorname{T}} \\
\boldsymbol{U}^{\operatorname{T}}\boldsymbol{A}\boldsymbol{U}=(\boldsymbol{D}_{\sqrt{m}})^2
\end{equation}
Y usando el hecho de que $\boldsymbol{A}$ es diagonalizado de la forma
\begin{equation}
\boldsymbol{A}=\boldsymbol{U} \boldsymbol{D} \boldsymbol{U}^{\operatorname{T}}
\end{equation}
Despejando $\boldsymbol{D}$ hallamos que
\begin{equation}
\boldsymbol{U}^{\operatorname{T}}\boldsymbol{A}\boldsymbol{U}=\boldsymbol{D} =(\boldsymbol{D}_{\sqrt{m}})^2
\end{equation}
Asi los autovalores de $A$ son la raiz de los autovalores de $Y$