# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
import numpy as np
import random as rd

In [2]:
#th=th12,th23,th13
th = (0,np.deg2rad(33.82), np.deg2rad(48.3), np.deg2rad(8.61))
#s=s12,s23,s13
s=np.sin(th)
c=np.cos(th)

m1=10**rd.randrange(-9,-4)

#def deltas
dm21=7.39e-05
dm32=2.449e-03
#def U
U=[[c[1]*c[3], s[1]*c[3], s[3]],
   [-s[1]*c[2]-c[1]*s[3]*s[2], c[1]*c[2]-s[1]*s[3]*s[2], c[3]*s[2]],
   [s[1]*s[2]-c[1]*s[3]*c[2], -c[1]*s[2]-s[1]*s[3]*c[2], c[3]*c[2]]]
Ut=np.transpose(U)

In [3]:
print(Ut)
print('\n',m1)

[[ 0.82142745 -0.46312144  0.33282949]
 [ 0.55031308  0.49045305 -0.67573021]
 [ 0.14970791  0.73822377  0.65773339]]

 1e-05


In [4]:
#def m2, m3
m2=(dm21+m1**2)**0.5
m3=(dm32+m2**2)**0.5
print(m2, m3)

0.00859651673644622 0.05022847897358629


In [5]:
#ángulos random alphas
tha=[0]
for i in range(3):
  tha.append(rd.random()*2*np.pi)
tha=tuple(tha)

In [6]:
s=np.sin(tha)
c=np.cos(tha)
#reciclo la definición de U para R
R=np.array([[c[1]*c[3], s[1]*c[3], s[3]],
   [-s[1]*c[2]-c[1]*s[3]*s[2], c[1]*c[2]-s[1]*s[3]*s[2], c[3]*s[2]],
   [s[1]*s[2]-c[1]*s[3]*c[2], -c[1]*s[2]-s[1]*s[3]*c[2], c[3]*c[2]]])
#def D
D=np.diag([m1**0.5,m2**0.5,m3**0.5])

print(D)
print(R)

[[0.00316228 0.         0.        ]
 [0.         0.0927174  0.        ]
 [0.         0.         0.22411711]]
[[-0.71960797  0.55666548 -0.41507578]
 [-0.69251448 -0.5315447   0.48773347]
 [ 0.05087306  0.63842288  0.76800271]]


In [7]:
#def Y
Y=np.dot(np.dot(R,D),R.T)#R@D@Ut
Y

array([[ 0.06898115, -0.0712302 , -0.03860902],
       [-0.0712302 ,  0.08102677,  0.05237484],
       [-0.03860902,  0.05237484,  0.16998888]])

In [8]:
#A=Yt.Y
A=np.dot(np.transpose(Y),Y)
np.linalg.eig(A)

(array([5.02284790e-02, 1.00000000e-05, 8.59651674e-03]),
 array([[-0.41507578,  0.71960797,  0.55666548],
        [ 0.48773347,  0.69251448, -0.5315447 ],
        [ 0.76800271, -0.05087306,  0.63842288]]))

In [9]:
U

[[0.8214274508457405, 0.5503130783189389, 0.14970791170877362],
 [-0.4631214436194727, 0.49045305045856263, 0.738223769432891],
 [0.33282949306947573, -0.6757302132708172, 0.6577333862714374]]

En efecto, los valores y vectores propios de A=Yt.Y son correctos

In [10]:
#Si los autovalores de Y son la raíz de los autovalores de A su suma es 0
print(np.linalg.eigvals(A)**0.5-np.linalg.eigvals(Y))

[-2.77555756e-17 -9.24173932e-16  1.38777878e-17]


Es correcto, esto se debe a que $A=Y^TY$, luego $diag(m_i)=UAU^T=UY^TYU^T=UY^TU^TUYU^T=diag(eigvals(Y^T))diag(eigvals(Y))=diag(eigvals(Y))^2$