# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

Where $\Delta m^2_{ij}=m^2_i-m^2_j$

In [50]:
import numpy as np
import scipy.linalg as la


In [89]:
m1=(10e-7) #eV2 #Valor dado
m21=(7.39+0.21)*10e-5 #eV2

m2=np.sqrt(m21+m1**2) #Se encuentra m2 a partir de el m21 de la tabla y m1 definido.


In [98]:
np.sqrt(10e-7)

0.001

In [90]:
m32=(2.449+0.032)*10e-3 #Delta m32.

m3=np.sqrt(m32+(m2**2)) #Se encuentra m3 a partir de el m32 de la tabla y m2 encontrado anteriormente.

In [91]:
m2,m3

(0.02756809752231735, 0.15990622252120146)

In [92]:
alf12=0.5 #Se usan los alfas ij para remplazarlos en la matriz R.
alf13=np.pi/4 #Se define alfa entre para 12, 13 y 23 (0,2pi)
alf23=np.pi

* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

In [93]:
#Se definen los cji^alfa usando los alfa anteriores.
c12a=np.cos(alf12)
c13a=np.cos(alf13)
c23a=np.cos(alf23)

#Se definen los sji^alfa usando los alfa anteriores.

s12a=np.sin(alf12)
s13a=np.sin(alf13)
s23a=np.sin(alf23)

In [94]:
#Se ubican los cji^alfa y sji^alfa  usando la referencia de matriz R dada, por cada fila.
r1=([c12a*c13a, s12a*c13a, s13a])
r2=([-s12a*c23a-c12a*s13a*s23a, c12a*c23a-s12a*s13a*s23a, c13a*s23a])
r3=([s12a*s23a-c12a*s13a*c23a, -c12a*s23a-s12a*s13a*c23a, c13a*c23a])

R=np.asmatrix(np.array([r1,r2,r3])) #Matriz R.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

In [95]:
D=np.diag(np.array([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)]), 0)
D #Matriz D, usando las raices de m1, m2 y m3.

array([[0.001     , 0.        , 0.        ],
       [0.        , 0.16603643, 0.        ],
       [0.        , 0.        , 0.39988276]])


Where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that


In [33]:
ot=[33.82+0.78, 48.3+1.2, 8.61+0.13] #[012, 023, 013] #Angulos encontrados en la tabla asignada.
o=np.radians(ot)

#Se definen los cji usando los angulos anteriores.
c12=np.cos(o[0])
c23=np.cos(o[1])
c13=np.cos(o[2])

#Se definen los sji usando los angulos anteriores.
s12=np.sin(o[0])
s23=np.sin(o[1])
s13=np.sin(o[2])

In [34]:
#Se define la matriz U usando la teoria anterior y los cij y sij encontrados.
u1=([c12*c13, s12*c13, s13])
u2=([-s12*c23-c12*s13*s23, c12*c23-s12*s13*s23, c13*s23])
u3=([s12*s23-c12*s13*c23, -c12*s23-s12*s13*c23, c13*c23])


U=np.asmatrix(np.array([u1,u2,u3])) #Matriz U usando u1, u2, u3.

In [68]:
U 

matrix([[ 0.81357815,  0.56124997,  0.15195088],
        [-0.46389377,  0.46897317,  0.75157617],
        [ 0.35056121, -0.68195501,  0.64190669]])

In [35]:
UT=np.transpose(U) #Matriz traspuesta de U.


$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$

In [75]:
Y=R@D@UT #Se encuentra la matriz usando la teoria dada.
YT=np.transpose(Y)

$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

In [99]:
A=YT@Y #Se usa la teoria dada para definir A usando la Y encontrada.
A

matrix([[0.01237674, 0.02551757, 0.00504565],
        [0.02551757, 0.09638913, 0.06832849],
        [0.00504565, 0.06832849, 0.07870945]])

In [102]:
λ1,V1=np.linalg.eig( A ) #Se usa linealg para obtener los valores y vectores propios de A

In [103]:
λ1 #Los valores propios coinciden con m3, m1, m2.

array([1.59906223e-01, 1.00000000e-06, 2.75680975e-02])

In [111]:
-V1 #Los vectores propios de A coinciden con la matriz -U.

matrix([[ 0.15195088,  0.81357815,  0.56124997],
        [ 0.75157617, -0.46389377,  0.46897317],
        [ 0.64190669,  0.35056121, -0.68195501]])

In [105]:
λ2,V2=np.linalg.eig( Y) #Se usa linealg para obtener los valores y vectores propios de Y

In [106]:
λ2 #Valores propios de Y, el primer valor propio es la raiz de m2 (valor propio de A.)

array([ 0.00198866+0.j        , -0.10757851+0.14769457j,
       -0.10757851-0.14769457j])

$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$

In [107]:
T=UT@A@U 
T #Matriz UT*A*U, en su diagonal están los valores propios de A, lo cuales son m1, m2, m3.

matrix([[ 1.00000000e-06,  3.67051140e-18,  1.16697847e-17],
        [ 1.73472348e-18,  2.75680975e-02, -2.60208521e-17],
        [ 1.38777878e-17, -1.38777878e-17,  1.59906223e-01]])

In [108]:
M=[T[0,0],T[1,1],T[2,2]] #Diagonal de la matriz anterior, la cual coincide con m1,m2 y m3.
M

[9.9999999999767e-07, 0.027568097522317345, 0.15990622252120146]