# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
#Librerías 
import numpy as np

In [2]:
"""Punto 1"""
np.random.seed(1007374246) # semilla para los números aleatorios
m1 = 10**(round(np.random.uniform(-9,-4))) # Se obtiene m1 aleatorio 
Δsquarem21 = 7.39*10e-5 # Diferencia de las masas 21
Δsquarem32 = 2.449*10e-3 # Diferencia de las masas 32
m2 = np.sqrt(Δsquarem21+m1**2) # se calcula m2
m3 = np.sqrt(Δsquarem32+m2**2) # Se calcula m3
m1,m2,m3

(1e-08, 0.027184554438138213, 0.15883639381451625)

In [3]:
"""Punto 2"""
np.random.seed(1007374246)
α12 = np.random.uniform(0,2*np.pi) #Se calculan los angulos de forma aleatoria
α13 = np.random.uniform(0,2*np.pi)
α23 = np.random.uniform(0,2*np.pi)

α12,α13,α23

(1.0958699824467912, 4.520198029015211, 3.6184432432729237)

In [4]:
"""Punto 3"""
def Ortogonal(α12,α13,α23):
#Función para calcular R y U
  return np.array([[np.cos(α12)*np.cos(α13),                                       np.sin(α12)*np.cos(α13),                                      np.sin(α13)],
                  [-np.sin(α12)*np.cos(α23)-np.cos(α12)*np.sin(α13)*np.sin(α23),   np.cos(α12)*np.cos(α23)-np.sin(α12)*np.sin(α13)*np.sin(α23),  np.cos(α13)*np.sin(α23) ],
                  [np.sin(α12)*np.sin(α23)-np.cos(α12)*np.sin(α13)*np.cos(α23),   -np.cos(α12)*np.sin(α23)-np.sin(α12)*np.sin(α13)*np.cos(α23),  np.cos(α13)*np.cos(α23)]
                  ])

R = Ortogonal(α12,α13,α23) # Se calcula la matriz R
D_sqrtm=np.diag( np.sqrt([m1,m2,m3]) ) # Matriz diagonal con las raices de las masas

θ12 = np.deg2rad(33.82)#Angulos tomados de la tabla de datos
θ23 = np.deg2rad(48.3)
θ13 = np.deg2rad(8.61)

U = Ortogonal(θ12,θ13,θ23) # Se calcula U para los angulos de la tabla
Y=np.dot( np.dot( R,D_sqrtm), U.transpose() ) # Se calcula Y
Y

array([[-0.07398668, -0.30252921, -0.23838575],
       [-0.06793751, -0.03948549,  0.11290337],
       [-0.04126838,  0.00422174,  0.10748284]])

In [5]:
"""Punto 4"""
A=np.dot( Y.transpose(), Y)#Se encuentra la matriz A
λA,UA=np.linalg.eig(A) #Se optienen obtienen los autovalores y autovectores de A
print('Autovalores={}'.format(λA))
print('Masas={}'.format([m3,m1,m2]))
print('Matriz U=')
U =UA #Se encuentra la matriz de Autovectores 
U

Autovalores=[1.58836394e-01 1.00000000e-08 2.71845544e-02]
Masas=[0.15883639381451625, 1e-08, 0.027184554438138213]
Matriz U=


array([[-0.14970791, -0.82142745, -0.55031308],
       [-0.73822377,  0.46312144, -0.49045305],
       [-0.65773339, -0.33282949,  0.67573021]])

Notamos que los autovalores corresponden con los valores de las masas m1, m2 y m3.

In [6]:
"""Punto 5"""
np.array(sorted([np.linalg.eigvals(A)]))**0.5-np.array(sorted(np.linalg.eigvals(Y)))#se hace la resta de los autovalores de A^0.5 y Y

array([[ 6.01834978e-01,  2.63689978e-04, -3.25891137e-02]])

Notamos que la diferencia entre los valores de los autovalores de A a la (1/2) y los autovalores de Y no son cero, pero si se aproximan a este valor. Esta diferencia se puede entender como consecuencia de la no consideración de $δ_{CP}$. 