# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

PUNTO 1

In [37]:
#libreríaa
import random
import numpy as np

In [145]:
#determinacion de m1, m2, m3, deterinando m1 con valor aleatorio entre (10e-9,10e-4)

m1 = random.uniform((10e-9) , (10e-4))

print("valor para m1 = ", m1)

m2 = np.sqrt((7.39) * (10**-5) + (m1**2))

print ("valor para m2 =", m2)

m3 = np.sqrt((2.449) * (10**-3) + (m2 ** 2))

print ("valor para m3 = ", m3)

#rectificación del orden de m1,m2,m3
if m1<m2<m3:
  print ("true")

valor para m1 =  0.00026502529786924864
valor para m2 = 0.008600595235709602
valor para m3 =  0.0502291771623676
true


PUNTO 2

In [146]:
#Determinacion de alpha12, alpha23, alpha13 con valores aleatorios entre (0,2pi)

alpha12 = random.uniform(0,2*np.pi)

print("valor para alpha12 =",alpha12)

alpha23 = random.uniform(0,2*np.pi)

print("valor para alpha12 =",alpha23)

alpha13 = random.uniform(0,2*np.pi)

print("valor para alpha12 =",alpha13)

valor para alpha12 = 1.2439459330613827
valor para alpha12 = 2.7959883805195034
valor para alpha12 = 5.435725396531059


In [147]:
# Ahora convertimos los valores de la tabla para 33.82 , 8.61 y 48.3 en radianes
theta12 = np.deg2rad(33.82) 
theta13 = np.deg2rad(8.61)  
theta23 = np.deg2rad(48.3)

print( "valor para theta12 en radianes = ",theta12 )
print( "valor para theta13 en radianes = ",theta13 )
print( "valor para theta23 en radianes = ",theta23 )

valor para theta12 en radianes =  0.5902703530244823
valor para theta13 en radianes =  0.15027284859671178
valor para theta23 en radianes =  0.8429940287132611


In [148]:
#Como nos muestra el ejemplo para U hallamos sus corespondientes valores s12,s13,s23,c12,c13,c23

s12 = np.sin(theta12)
s13 = np.sin(theta13)
s23 = np.sin(theta23)

c12 = np.cos(theta12) 
c13 = np.cos(theta13)
c23 = np.cos(theta23)


Ahora resolvemos usando

$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$

In [162]:
u1 = np.matrix([[1,0,0],[0,c23,s23],[0,-s23,c23]])

u2 = np.matrix([[c13,0,s13],[0,1,0],[-s13,0,c13]])

u3 = np.matrix([[c12,s12,0],[-s12,c12,0],[0,0,1]])

#Hallado el Valor de U

U = u1*u2*u3
print("Valor de la matriz U =")
U

Valor de la matriz U =


matrix([[ 0.82142745,  0.55031308,  0.14970791],
        [-0.46312144,  0.49045305,  0.73822377],
        [ 0.33282949, -0.67573021,  0.65773339]])

In [163]:
#Encontramos los valores de la matriz R con respecto a los alphas genrados en el principio

sa12 = np.sin(alpha12)
sa13 = np.sin(alpha13)
sa23 = np.sin(alpha23)

ca12 = np.cos(alpha12)
ca13 = np.cos(alpha13)
ca23 = np.cos(alpha23)




Ahora hallamos el valor de R usando
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$

In [164]:
#Hallando cada valor de la matriz R

r11 = ca12*ca13
r12 = sa12*ca13
r13 = sa13

r21 = (-sa12*ca23)-(ca12*sa13*sa23)
r22 = (ca12*ca23)-(sa12*sa13*sa23)
r23 = ca13*sa23

r31 = (sa12*sa23)-(ca12*sa13*ca23)
r32 = (-ca12*sa23)-(sa12*sa13*ca23)
r33 = ca13*ca23

#Ahora hallando r con sus respectivos valores

print("Valor de la matriz R =")
R = np.array([[r11,r12,r13],[r21,r22,r23],[r31,r32,r33]])
R

Valor de la matriz R =


array([[ 0.21250736,  0.62684776, -0.74960157],
       [ 0.97258967, -0.06158266,  0.22422513],
       [ 0.09439256, -0.77670423, -0.62275243]])

In [165]:
#Hallando las Traspuesta de U
UT = np.transpose(U)
print("Valor para la traspuesta de U =")
UT

Valor para la traspuesta de U =


matrix([[ 0.82142745, -0.46312144,  0.33282949],
        [ 0.55031308,  0.49045305, -0.67573021],
        [ 0.14970791,  0.73822377,  0.65773339]])

In [166]:
#Ahora hallamos la diagonal de la raiz de los valores m1,m2,m3

Dm = np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)])
print("valor para lamatriz diagonal de las raices de los valores m1,m2,m3")
Dm

valor para lamatriz diagonal de las raices de los valores m1,m2,m3


array([[0.0162796 , 0.        , 0.        ],
       [0.        , 0.09273939, 0.        ],
       [0.        , 0.        , 0.22411867]])

PUNTO 3

Para hallar Y usamos 
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$

In [167]:
# Valor de Y

Y = R*Dm*UT
print("Valor para la matriz Y")
Y

Valor para la matriz Y


matrix([[ 0.00284176, -0.00160218,  0.00115144],
        [-0.00314291, -0.00280105,  0.00385919],
        [-0.0208948 , -0.10303422, -0.09180014]])

PUNTO 4

Para hallar A usamos

$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

In [168]:
#Traspuesta de Y
YT = np.transpose(Y)
print("Valor de la matriz traspuesta de Y")
YT

Valor de la matriz traspuesta de Y


matrix([[ 0.00284176, -0.00314291, -0.0208948 ],
        [-0.00160218, -0.00280105, -0.10303422],
        [ 0.00115144,  0.00385919, -0.09180014]])

In [169]:
#Valor de la matriz A
A = YT*Y
print("Valor para la matriz A")
A

Valor para la matriz A


matrix([[0.00045455, 0.00215713, 0.00190929],
        [0.00215713, 0.01062646, 0.0094459 ],
        [0.00190929, 0.0094459 , 0.00844348]])

In [170]:
#Sacamos los valores y vecotores propios
print("Valores y Vectores propios de A")
vectprop = np.linalg.eig(A)
vectprop

Valores y Vectores propios de A


(array([1.94799088e-02, 1.19683774e-05, 3.26171079e-05]),
 matrix([[-0.14970791, -0.82142745, -0.55031308],
         [-0.73822377,  0.46312144, -0.49045305],
         [-0.65773339, -0.33282949,  0.67573021]]))

Hallamos los autovalores usando
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}
$$

In [171]:
#Autovalores de la matriz
print("Autovalores")
autoval =UT*A*U
autoval

Autovalores


matrix([[ 1.19683774e-05,  2.08376830e-19,  1.47662158e-19],
        [ 2.86265519e-19,  3.26171079e-05, -1.00069896e-18],
        [ 7.00130178e-19, -1.83905680e-18,  1.94799088e-02]])

Para hallar los autovectores usamos
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

In [172]:
#Autovector  U1

avect1 = np.array([[c12*c13],[-(s12*c23)-(c12*s13*s23)],[(s12*s23)-(c12*s13*c23)]])
print("Autovector U1")
avect1

Autovector U1


array([[ 0.82142745],
       [-0.46312144],
       [ 0.33282949]])

In [173]:
#Autovector  U2

avect2 = np.array([[s12*c13],[(c12*c23)-(s12*s13*s23)],[(-c12*s23)-(s12*s13*c23)]])
print("Autovector U2")
avect2

Autovector U2


array([[ 0.55031308],
       [ 0.49045305],
       [-0.67573021]])

In [174]:
#Autovecto  U3

avect3 = np.array([[s13],[c13*s23],[c13*c23]])
print("Autovector U3")
avect3

Autovector U3


array([[0.14970791],
       [0.73822377],
       [0.65773339]])

Se  puede ver que los Autovectores coinciden con los Autovectores de A

Punto 5
Rectificación con diferencia de Autovalores

In [181]:
print("Autovalores de Y al cuadrado")
(np.linalg.eigvals(Y)** 2), np.linalg.eigvals(A)

Autovalores de Y al cuadrado


(array([7.52092449e-03, 1.33777802e-05, 7.55809525e-05]),
 array([1.94799088e-02, 1.19683774e-05, 3.26171079e-05]))

In [182]:
print("Diferencia entre valores propios")
(np.linalg.eigvals(Y) ** 2)[0] - np.linalg.eigvals(A)[0] 


Diferencia entre valores propios


-0.011958984282256035

In [183]:
print("Diferencia entre valores propios")
(np.linalg.eigvals(Y) ** 2)[1] - np.linalg.eigvals(A)[1] 


Diferencia entre valores propios


1.4094027637991065e-06

In [184]:
print("Diferencia entre valores propios")
(np.linalg.eigvals(Y) ** 2)[2] - np.linalg.eigvals(A)[2] 

Diferencia entre valores propios


4.2963844637537106e-05