# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [340]:
#1)
import numpy as np
import random as rd

In [341]:
m1 = (10 ** rd.randint(-9, -4)) # [eV] # m1 aleatorio 
m2 = np.sqrt(7.39 * (10**(-5)) + m1 ** 2) # m2 a partir de la tabla
m3 = np.sqrt(2.449 * (10**(-3)) + m2 ** 2) # m3 a partir de la tabla 

print(m1, m2, m3)

0.0001 0.00859709253178073 0.05022857752315906


In [342]:
#2)

In [343]:
alpha_12 = rd.uniform(0, 2 * np.pi) # alpha12 aleatorio entre 0 y 2pi
alpha_13 = rd.uniform(0, 2 * np.pi) # alpha13 aleatorio entre 0 y 2pi
alpha_23 = rd.uniform(0, 2 * np.pi) # alpha23 aleatorio entre 0 y 2pi

print(alpha_12, alpha_13, alpha_23)

0.687847691766626 4.6734225606494295 3.6243737837939354


In [344]:
#3)

$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$

In [345]:
theta12 = np.deg2rad(33.82) # generamos theta12 en radianes a partir de la iamgen 
theta13 = np.deg2rad(8.61)  # generamos theta13 en radianes a partir de la iamgen 
theta23 = np.deg2rad(48.3)  # generamos theta23 en radianes a partir de la iamgen 

# generamos los valores que corresponden a la matriz U 
co12 = np.cos(theta12) 
co13 = np.cos(theta13)
co23 = np.cos(theta23)

si12 = np.sin(theta12)
si13 = np.sin(theta13)
si23 = np.sin(theta23)

# generamos las matrices que daran la matriz U
u1 = np.matrix([[1, 0,  0],
                [0,co23,si23],
                [0,-si23,co23]])

u2 = np.matrix([[co13, 0,  si13],
                [0,    1,   0],
                [-si13, 0, co13]])

u3 = np.matrix([[co12, si12,  0],
                [-si12, co12,  0],
                [0,     0,  1]])

U = u1 * u2 * u3 # Matriz U
U_T = np.transpose(U) # Matriz U transpuesta

print(U)
print("\n")
print(U_T)

[[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]]


[[ 0.82142745 -0.46312144  0.33282949]
 [ 0.55031308  0.49045305 -0.67573021]
 [ 0.14970791  0.73822377  0.65773339]]


$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$

In [346]:
D_sqrt_m = np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)]) # Matriz diagonal con los autovalores de A

# generamos los valores que corresponden a la matriz R
c12 = np.cos(alpha_12)
c13 = np.cos(alpha_13)
c23 = np.cos(alpha_23)

s12 = np.sin(alpha_12)
s13 = np.sin(alpha_13)
s23 = np.sin(alpha_23)


R11, R12, R13 = c12 * c13 , s12 * c13, s13
R21, R22, R23= -s12 * c23 - c12 * s13 * s23, c12 * c23 - s12 * s13 * s23, c13 * s23
R31, R32, R33 = s12 * s23 - c12 * s13 * c23, -c12 * s23 - s12 * s13 * c23, c13 * c23 

# R ortogonal 3x3 con rotacion de angulos alpha_ij
R = np.array([[R11, R12, R13],
             [R21, R22, R23],
             [R31, R32, R33]])

print(R)

[[-0.03009839 -0.02473257 -0.99924091]
 [ 0.2039046  -0.9788237   0.01808536]
 [-0.97852798 -0.20320548  0.03450411]]


In [347]:
Y = R * D_sqrt_m * U_T # Matriz Y 
Y_T = np.transpose(Y) # Matriz Y transpuesta

print(Y)
print("\n")
print(Y_T)

[[-0.00024724  0.00013939 -0.00010018]
 [-0.04994478 -0.04451206  0.06132727]
 [ 0.00115769  0.00570866  0.00508623]]


[[-0.00024724 -0.04994478  0.00115769]
 [ 0.00013939 -0.04451206  0.00570866]
 [-0.00010018  0.06132727  0.00508623]]


In [348]:
#4)

In [349]:
A = Y_T * Y  # Matriz A
np.linalg.eig(A) # Valores y Vectores propios 

(array([8.23683854e-03, 9.05913265e-08, 5.97987966e-05]),
 matrix([[-0.55031308, -0.82142745,  0.14970791],
         [-0.49045305,  0.46312144,  0.73822377],
         [ 0.67573021, -0.33282949,  0.65773339]]))

In [350]:
(U_T * A * U).round(5) # autovalores 

array([[ 0.00e+00,  0.00e+00, -0.00e+00],
       [-0.00e+00,  8.24e-03,  0.00e+00],
       [-0.00e+00,  0.00e+00,  6.00e-05]])

In [351]:
# Autevector 1
av1 = np.array([[co12 * co13],
              [-si12 * co23 - co12 * si13 * si23],
              [si12 * si23 - co12 * si13 * co23]])

# Autovector 2
av2 = np.array([[si12 * co13], 
                [co12 * co23 - si12 * si13 * si23], 
                [-co12 * si23 - si12 * si13 * co23]])

# Autovector 3
av3 = np.array([[si13], 
                [co13 * si23], 
                [co13 * co23]])
# coinciden con los autovectores de A

print(av1)
print("\n")
print(av2)
print("\n")
print(av3)

[[ 0.82142745]
 [-0.46312144]
 [ 0.33282949]]


[[ 0.55031308]
 [ 0.49045305]
 [-0.67573021]]


[[0.14970791]
 [0.73822377]
 [0.65773339]]


In [352]:
#5)

In [353]:
(np.linalg.eigvals(Y) ** 2), np.linalg.eigvals(A)
# auto valores de Y al cuadrado y para 

(array([2.56462858e-03, 1.35368426e-07, 1.28528003e-04]),
 array([8.23683854e-03, 9.05913265e-08, 5.97987966e-05]))

In [354]:
(np.linalg.eigvals(Y) ** 2)[0] - np.linalg.eigvals(A)[0] 
# esta es la diferencia entre los dos valores propios, es una diferencia muy pequeña

-0.0056722099544083415

In [355]:
(np.linalg.eigvals(Y) ** 2)[1] - np.linalg.eigvals(A)[1] 
# esta es la diferencia entre los dos valores propios, es una diferencia muy pequeña

4.477709959713203e-08

In [356]:
(np.linalg.eigvals(Y) ** 2)[2] - np.linalg.eigvals(A)[2] 
# esta es la diferencia entre los dos valores propios, es un valor muy pequeña

6.87292060249723e-05