# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import random

### Punto 1:   Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.

In [2]:
#numero aleatorio entre 1e-9 y 1e-4
m1 = random.uniform(1e-9,1e-4)
m1

1.5406146972492148e-05

se tiene que:

$\frac { \Delta  m^2_{21}}{10^-5 eV^2}=7.39 $ (1)

$\frac { \Delta  m^2_{32}}{10^-3 eV^2}=2.44 $ (2)

$\Delta m^2_{ij}=m^2_i-m^2_j$ (3)

se reemplaza (3) en (1) y (2) y se despejan m2 y m3 de la siguiente forma:

$\frac { m^2_2-m^2_1}{10^-5 eV^2}=7.39 $

$ m_2=\sqrt{7.39(10^-5)+m^2_1} $ (3)

y


$\frac { m^2_3-m^2_2}{10^-3 eV^2}=2.44 $

$ m_3=\sqrt{2.44(10^-3)+m^2_2} $ (4)



In [3]:
m2 = np.sqrt((7.39e-5)+m1**2)
m2

0.008596524725106334

In [4]:
m3 = np.sqrt(2.44e-3+m2**2)
m3

0.050138809692187196

In [5]:
# asegurando que m1<m2<m3
m = [m3,m2,m1]
m.sort()
print(m)

[1.5406146972492148e-05, 0.008596524725106334, 0.050138809692187196]


### Punto 2: Choose random values for $\alpha_{ij}$  between $(0,2\pi)$

In [6]:
#valores random de aplha en radianes 
a12 = random.uniform(0,2*np.pi)
a13 = random.uniform(0,2*np.pi)
a23 = random.uniform(0,2*np.pi)

print(a12,a13,a23)

3.957756338178937 1.5933177471300743 2.338007256650127


### Punto 3:Obtain $\boldsymbol{Y}$


In [7]:
#valores de theta convertidos a radianes
θ12 = np.radians(33.82)
θ13 = np.radians(8.61)
θ23 = np.radians(48.3)

print(θ12,θ13,θ23)

0.5902703530244823 0.15027284859671178 0.8429940287132611


In [8]:
#matriz diagonal de m1,m2,m3
d1 = np.array([m1,0,0])
d2 = np.array([0,m2,0])
d3 = np.array([0,0,m3])
d = np.array([d1,d2,d3])
D = np.asmatrix(d)
Dr = np.sqrt(D)  #Dr es la raiz cuadrada de la matriz D


In [9]:
#senos y cosenos con valores de aplha
c12 = np.cos(a12)
c13 = np.cos(a13)
c23 = np.cos(a23)
s12 = np.sin(a12)
s13 = np.sin(a13)
s23 = np.sin(a23)

In [10]:
#matriz R
r1 = np.array([c12*c13,s12*c13,s13])
r2 = np.array([(-s12*c23)-(c12*s13*s23),(c12*c23)-(s12*s13*s23),c13*s23])
r3 = np.array([(s12*s23)-(c12*s13*c23),(-c12*s23)-(s12*s13*c23),c13*c23])
r = np.array([r1,r2,r3])
R = np.asmatrix(r)


In [11]:
#senos y cosenos con valores de theta
C12 = np.cos(θ12)
C13 = np.cos(θ13)
C23 = np.cos(θ23)
S12 = np.sin(θ12)
S13 = np.sin(θ13)
S23 = np.sin(θ23)


In [12]:
#matrix U
u1 = np.array([C12*C13,S12*C13,S13])
u2 = np.array([(-S12*C23)-(C12*S13*S23),(C12*C23)-(S12*S13*S23),C13*S23])
u3 = np.array([(S12*S23)-(C12*S13*C23),(-C12*S23)-(S12*S13*C23),C13*C23])
u = np.array([u1,u2,u3])
U = np.asmatrix(u)

In [13]:
#matrix Y
Y = R @ Dr @ U.T
Y

matrix([[ 0.03440047,  0.16597691,  0.1462326 ],
        [ 0.05042843,  0.04280736, -0.06504275],
        [-0.00333474,  0.00383518,  0.00177605]])

### Punto 4: Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors

 

In [14]:
#matrix A
A = Y.T @ Y
A

matrix([[0.00373754, 0.0078556 , 0.00174454],
        [0.0078556 , 0.02939551, 0.02149374],
        [0.00174454, 0.02149374, 0.02561769]])

In [15]:
# E=autoovalores, V=autovectores de la matriz A
E,V = la.eig(A)
print(E) #vemos que los auto valores de a son m1,m2 y m3 pero en desorden
print(m1,m2,m3)

[5.01388097e-02+0.j 1.54061470e-05+0.j 8.59652473e-03+0.j]
1.5406146972492148e-05 0.008596524725106334 0.050138809692187196


In [16]:
#matriz de auto vectores en orden apropiado 
AU = U.T @ A @ U

print(AU)
#Vemos m1,m2,m3 en la diagonal de la matriz de autovectores y lo demas son ceros computacionales

[[ 1.54061470e-05  3.04829004e-19 -3.96268369e-19]
 [ 2.10633438e-19  8.59652473e-03  4.49198923e-19]
 [-1.84907466e-18 -1.09456649e-18  5.01388097e-02]]


### Punto 5:Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [17]:
print(E) #autovalores de la matriz A

[5.01388097e-02+0.j 1.54061470e-05+0.j 8.59652473e-03+0.j]


In [18]:
EY,VY = la.eig(Y) # EY=autovalores de la  matriz Y, VY=autovectores de la matriz Y
print(EY)

[ 0.13009614+0.j -0.03072773+0.j -0.02038452+0.j]


In [19]:
print(E**0.5) # raiz cuadrada de los valores propios de la matriz A

[0.22391697+0.j 0.00392507+0.j 0.09271745+0.j]


Rta/: se evidencia que los autovalores de Y son parecidos a la raiz cuadrada de los autovalores de A y se le atribuye el que no sean iguales a los errores en los valores de m1,m2,m3 que no se tomaron en cuenta
 
$A=Y^TY$

reemplanzando lo anterior


$diag(m_i)=UAU^T=UY^TYU^T=UY^TU^TUYU^T=diag(eigenvals(Y^T))diag(eigenvals(Y)=diag(eigenvals(Y^{T})*eigenvals(Y))$

pero sabemos que

$eigenvals(Y^T) = eigenvals(Y)$

$diag(eigenvals(Y^T)*eigenvals(Y))=diag(eigenvals(Y)^2)$

entonces


$UAU^{T}=diag(eigenvals(A))= diag(eigenvals(Y)^2)$



