# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.

### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
#librerias
import numpy as np
import sympy
import scipy.linalg as la
sympy.init_printing()

In [2]:
# Punto 1
m1 = np.random.uniform(10**-9,10**-4)

Δm21 = 7.39*(10**-5)
Δm32 = 2.449*(10**-3)

m2 = np.sqrt(Δm21 + m1**2)
m3 = np.sqrt(Δm32 + m2**2)

print(m1,m2,m3)

8.871687938301744e-05 0.008596968691619591 0.05022855632690121


In [3]:
#Punto 2

a = np.random.uniform(0,2*np.pi,3)                                          # Valores aleatorios entre 0 y pi

c12 = np.cos(a[0])                                                          #
c13 = np.cos(a[1])                                                          #
c23 = np.cos(a[2])                                                          #   Senos y cosenos para la 
s12 = np.sin(a[0])                                                          #   Matriz R
s13 = np.sin(a[1])                                                          #
s23 = np.sin(a[2])                                                          #

R = np.matrix([[c12*c13, s12*c13, s13],                                     #
               [-s12*c23-c12*s13*s23, c12*c23-s12*s13*s23, c13*s23],        # Matriz R
               [s12*s23-c12*s13*c23, -c12*s23-s12*s13*c23, c13*c23]])       #

D = np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)])

ta = np.array([33.82, 48.3, 8.61])
t = np.deg2rad(ta)

c12 = np.cos(t[0])                                                          #
c13 = np.cos(t[1])                                                          #
c23 = np.cos(t[2])                                                          #   Senos y cosenos para la 
s12 = np.sin(t[0])                                                          #   Matriz U
s13 = np.sin(t[1])                                                          #
s23 = np.sin(t[2])                                                          #

U = np.matrix([[c12*c13, s12*c13, s13],                                     #
               [-s12*c23-c12*s13*s23, c12*c23-s12*s13*s23, c13*s23],        # Matriz U
               [s12*s23-c12*s13*c23, -c12*s23-s12*s13*c23, c13*c23]])       #

UT = np.transpose(U)                                                        # Matriz U transpuesta



#Punto 3

Y = R*D*UT                                                                  # Matriz Y 
print("La matriz Y esta dada por: \n")
sympy.Matrix( Y )

La matriz Y esta dada por: 



⎡ 0.158135809531013    0.018342342302542    0.136347773094114 ⎤
⎢                                                             ⎥
⎢-0.064141946379706   -0.0417822615887097  -0.0312664532199778⎥
⎢                                                             ⎥
⎣0.00924017040156565  0.0583782270929785   -0.0681851521933961⎦

In [4]:
print(U)

[[ 0.55266688  0.37025767  0.74663818]
 [-0.64317685  0.75921362  0.09959025]
 [-0.52998382 -0.53526063  0.65773339]]


In [5]:
#Punto 4 

YT = np.transpose(Y)                  # Matriz Y transpuesta

A = YT * Y                            #Matriz A

V, U = la.eig(A)                      #Se calculan los vectores y autovalores 

print("La matriz A esta dada por: \n")
sympy.pprint(sympy.Matrix(A))

u = np.asmatrix(U)                    #Matriz con los autovectores
v = np.diag(V, 0)                     #matriz diagonal con los autovalores

print("\nMatriz de los autovectores: \n")
sympy.pprint(sympy.Matrix(u))

print("\nlos autovalores obenitos anteriormente son: ", m1,m2,m3)
print("\nMatriz de los autovalores: \n")
sympy.Matrix(v)

La matriz A esta dada por: 

⎡0.0292065042904558   0.0061200014972337     0.0229369142167843  ⎤
⎢                                                                ⎥
⎢0.0061200014972337   0.00549021630313035   -0.000173207645445547⎥
⎢                                                                ⎥
⎣0.0229369142167843  -0.000173207645445547   0.0242175213043177  ⎦

Matriz de los autovectores: 

⎡-0.746638182285391   -0.552666882572449  -0.370257669280756⎤
⎢                                                           ⎥
⎢-0.0995902472005913  0.643176852657656   -0.759213618731854⎥
⎢                                                           ⎥
⎣-0.657733386271438    0.52998382344468   0.535260627611322 ⎦

los autovalores obenitos anteriormente son:  8.871687938301744e-05 0.008596968691619591 0.05022855632690121

Matriz de los autovalores: 



⎡0.0502285563269012           0                    0         ⎤
⎢                                                            ⎥
⎢        0           8.87168793830208e-5           0         ⎥
⎢                                                            ⎥
⎣        0                    0           0.00859696869161959⎦

In [6]:
#Punto 5 

m, n = la.eig(Y)          # Autovalores y vectores de Y

print("Autovalores de Y: \n")
print(np.abs(m))          #Autovalores de Y
print("\nRaiz cuadrada de los autovalores de A: \n")
print(np.abs(np.sqrt(V))) #Raiz cuadrada de los autovalores de A
print("\n")

Autovalores de Y: 

[0.14543014 0.01670735 0.0805544 ]

Raiz cuadrada de los autovalores de A: 

[0.22411728 0.00941896 0.09271984]




In [7]:
print(np.linalg.eigvals(A)**0.5)
print(np.linalg.eigvals(Y))

[0.22411728 0.00941896 0.09271984]
[ 0.14543014 -0.01670735 -0.0805544 ]


In [8]:
np.array(sorted([np.linalg.eigvals(A)]))**0.5-np.array(sorted(np.linalg.eigvals(Y)))

array([[ 0.30467168,  0.02612631, -0.0527103 ]])

Aunque no dan lo mismo, si dan parecidas con cierto margen de error

Ahora, que dieran iguales sería correcto pues $A = Y^T Y$, luego

$diag(m_i) = UAU^T = UY^TYU^t = diag(eigvals(Y^T))diag(eigvals(Y))=diag(eigvals(Y)^2) $