# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
 #Librerías
 import numpy as np
 import sympy

**PUNTO 1**

In [2]:
# Generamos el exponente aleatorio 
em1=np.random.uniform(-9,-4)

#Creamos m1 con el exponente aleatorio
m1= 10**(em1)

dm21 = 7.39*(10**-5)
dm32 = 2.449*(10**-3)

#Hallamos m2 y m3 a partir de m1
m2 = np.sqrt(dm21+m1**2)
m3 = np.sqrt(dm32+m2**2)

print("m1 es: ",m1)
print("m2 es: ",m2)
print("m2 es: ",m3)

m1 es:  7.160380205905267e-08
m2 es:  0.008596510920433191
m2 es:  0.05022847797818611


**PUNTO 2**

In [3]:

#Generamos 3 alfa aleatorios entre 0 y 2 pi
a=np.random.uniform(0,2*np.pi,3)

print("los alfa son: ",a)

los alfa son:  [0.88018558 1.65264934 5.1348925 ]


**PUNTO 3**

In [4]:
#Usando alfa

c12=np.cos(a[0])
c13=np.cos(a[1])
c23=np.cos(a[2])

s12=np.sin(a[0])
s13=np.sin(a[1])
s23=np.sin(a[2])

#Matriz R definida en el enunciado
R=np.matrix([[c12*c13,s12*c13,s13],
             [-s12*c23-c12*s13*s23,c12*c23-s12*s13*s23,c13*s23],
             [s12*s23-c12*s13*c23,-c12*s23-s12*s13*c23,c13*c23]])

#D definido en el enunciado
D=np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)])

#U por la definición de arriba

t=np.array([33.82,8.61,48.3]) #Theta definididos en el cuadro
t=t*np.pi/180

c12=np.cos(t[0])
c13=np.cos(t[1])
c23=np.cos(t[2])

s12=np.sin(t[0])
s13=np.sin(t[1])
s23=np.sin(t[2])

U=np.matrix([[c12*c13,s12*c13,s13],
             [-s12*c23-c12*s13*s23,c12*c23-s12*s13*s23,c13*s23],
             [s12*s23-c12*s13*c23,-c12*s23-s12*s13*c23,c13*c23]])

#Matriz U transpuesta
Ut=np.transpose(U)

#Y definido en el enunciado
Y=R*D*Ut

print("La matriz Y es: ")
sympy.Matrix(Y)

La matriz Y es: 


Matrix([
[0.0302124807344397,  0.162035055493007,   0.150859860811295],
[0.0516404544363093, 0.0560471253597812, -0.0492501295722751],
[0.0122338627461169,  0.006666933801815, -0.0216910634891237]])

**PUNTO 4**

In [5]:
#Matriz Y transpuesta
Yt=np.transpose(Y) 

#Matriz A definida en el enunciado
A=Yt*Y 

#Eigenvalores y eigenvectores de A
values,vectors=np.linalg.eig(A) 

#Comprobación de los eigenvalores
print(m1,m2,m3)
print(values,"\n")

#Comprobación de los eigenvectores
print(vectors,"\n")
print(U)

7.160380205905267e-08 0.008596510920433191 0.05022847797818611
[5.02284780e-02 7.16038021e-08 8.59651092e-03] 

[[-0.14970791 -0.82142745 -0.55031308]
 [-0.73822377  0.46312144 -0.49045305]
 [-0.65773339 -0.33282949  0.67573021]] 

[[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]]


**PUNTO 5**

In [7]:
#Observemos que los eigenvalores de Y corresponden con la raíz de los eigenvalores de A
np.array(sorted([np.linalg.eigvals(A)]))**0.5-np.array(sorted(np.linalg.eigvals(Y))) #Haciendo diferencia de ellos 

array([[ 0.29684893,  0.00082216, -0.04513756]])

La diferencia de los eigenvalores debería dar 0, pues
 $A=Y^TY$ entonces $diag(m_i)=UAU^T=UY^TYU^T=UY^TU^TUYU^T=diag(eigenvalues(Y^T))diag(eigenvalues(Y))=diag(eigenvalues(Y)^2)  $
 
 
 Debido a los errores experimentales observamos que aunque no es 0, es bastante cercano