# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

#Solución del Parcial

##Importación de librerías

In [164]:
import numpy as np
import random as random

##**Punto 1**

In [167]:
#Tenemos que el exponente de m1 será:
u = np.random.randint( -9, -4 )
m1 = 10**u

In [168]:
m1 #Este es el valor de m1

1e-05

In [169]:
#De acuerdo a los valores de la tabla, podemos hallar m2 y m3 respecto a m1
Δm21 = 7.39E-5
m2 = np.sqrt(Δm21 + m1**2)
Δm32 = 2.449E-3
m3 = np.sqrt(Δm32+m2)

In [170]:
#Nótese que se cumple el orden normal
m1 < m2 < m3

True

##**Punto 2**

In [172]:
#Construcción de los alfas aleatorios
alfas = np.zeros(3)
for i in range(3):
  alfas[i] = random.uniform(0,2*np.pi)

In [173]:
#Definición de los alfas individualmente
α12 = alfas[0]
α13 = alfas[1]
α23 = alfas[2]

##**Punto 3**

In [174]:
#De acuerdo a los valores de la tabla, definimos los thetas para la matriz U
θ12 = np.deg2rad(33.82)
θ23 = np.deg2rad(48.3)
θ13 = np.deg2rad(8.61)

In [175]:
#Definición de los coeficientes para construir la matriz U
c12 = np.cos(θ12)
s12 = np.sin(θ12)
c13 = np.cos(θ13)
s13 = np.sin(θ13)
c23 = np.cos(θ23)
s23 = np.sin(θ23)

In [180]:
#Definimos los valores de 3 columnas, tal que la multiplicación de estas matrices es igual a U

col1 = np.array([ [1,   0,   0],
                   [0, c23, s23],
                   [0, -s23,c23] ])

col2 = np.array([ [c13, 0,  s13],
                   [0,    1,   0],
                   [-s13, 0, c13] ])

col3 = np.array([ [c12, s12,   0],
                   [-s12, c12,  0],
                   [0,     0,   1] ])

In [185]:
#Construcción de la matriz U
U = np.dot(col1,np.dot(col2,col3))
U

array([[ 0.82142745,  0.55031308,  0.14970791],
       [-0.46312144,  0.49045305,  0.73822377],
       [ 0.33282949, -0.67573021,  0.65773339]])

In [186]:
#Construcción de la matriz diag(m1,m2,m3)
D_s = np.diag(np.sqrt([m1,m2,m3]))
D_s

array([[0.00316228, 0.        , 0.        ],
       [0.        , 0.0927174 , 0.        ],
       [0.        , 0.        , 0.32418768]])

In [187]:
#Definición de los coeficientes para construir la matriz R
c_12 = np.cos(α12)
s_12 = np.sin(α12)
c_13 = np.cos(α13)
s_13 = np.sin(α13)
c_23 = np.cos(α23)
s_23 = np.sin(α23)

In [189]:
#Definimos las filas para la matriz R
R1 = np.array([ c_12*c_13, c_13*s_13, s_13 ])
R2 = np.array([ -s_12*c_23 -c_12*s_13*s_23, c_12*c_23 - s_12*s_13*s_23, c_13*s_23 ])
R3 = np.array([ s_12*s_23 -c_12*s_13*c_23, -c_12*s_23 - s_12*s_13*c_23, c_13*c_23 ])

In [190]:
#Construcción de la matriz R
R = np.array( [ R1, R2, R3 ] )
R

array([[ 0.07498562, -0.07889128, -0.99686355],
       [ 0.23116523, -0.97288708, -0.00730532],
       [-0.97002051, -0.2298924 , -0.0788016 ]])

In [192]:
#Según su definición, construimos la matriz Y
Y = np.dot(R,np.dot(D_s,np.transpose(U)))
Y

array([[-0.05221177, -0.24226971, -0.20753867],
       [-0.04939428, -0.04632749,  0.05963887],
       [-0.01807416, -0.02789245, -0.00342053]])

##**Punto 4**

In [193]:
#Definimos la matriz A
A = np.dot(np.transpose(Y),Y)
A

array([[0.00549254, 0.01544178, 0.00795197],
       [0.01544178, 0.06161884, 0.04761282],
       [0.00795197, 0.04761282, 0.04664079]])

In [201]:
#Resolvemos el eigenproblem para A
W = np.linalg.eigvals(A)
E, V = np.linalg.eig(A)

In [203]:
np.sort(E) #Ordenamiento de mayor a menor, nótese que los autovalores coinciden con las m, con mínimos errores computacionales

array([9.99938565e-06, 8.54356850e-03, 1.05198602e-01])

In [205]:
#Reordenamiento de indices
index = np.abs(E).argsort()
index

array([1, 2, 0])

In [206]:
#Dado que los autovectores salen con signos opuestos, debemos multiplicar por -1 la matriz de autovectores
V = -V
V

array([[ 0.16741388,  0.82157381,  0.54496703],
       [ 0.7536887 , -0.46299578,  0.46646356],
       [ 0.63555168,  0.33264302, -0.69672282]])

In [215]:
#Reordenamiento de la matriz de autovectores, para que se vea claro que V coincide con U
np.c_[ tuple( np.c_[V[:,i]]  for i in range(3)) ]

array([[ 0.16741388,  0.82157381,  0.54496703],
       [ 0.7536887 , -0.46299578,  0.46646356],
       [ 0.63555168,  0.33264302, -0.69672282]])

In [216]:
#Reordenamiento de la matriz de autovectores, para que se vea claro que V coincide con U
V = np.c_[ tuple( np.c_[V[:,i]]  for i in index) ]
V

array([[ 0.82157381,  0.54496703,  0.16741388],
       [-0.46299578,  0.46646356,  0.7536887 ],
       [ 0.33264302, -0.69672282,  0.63555168]])

In [234]:
#Nótese que el error en la resta de valores uno a uno entre V y U es relativamente pequeño
abs(V-U)

array([[0.00014636, 0.00534605, 0.01770596],
       [0.00012567, 0.02398949, 0.01546493],
       [0.00018647, 0.02099261, 0.02218171]])

##**Punto 5**

In [231]:
#Resolvemos el eigenproblem para Y
E1, V1 = np.linalg.eig(Y)
E1 = abs(E1)
E1 = np.sort(E1)
E1

array([0.00787426, 0.07234036, 0.16642589])

In [232]:
#Autovalores de Y elevados al cuadrado
E2 = E1**2
E2

array([6.20039702e-05, 5.23312737e-03, 2.76975776e-02])

In [233]:
#Nótese la diferencia entre los autovalores de A y los autovalores de Y elevados al cuadrado
abs(np.sort(E) - E2)

array([5.20045846e-05, 3.31044113e-03, 7.75010243e-02])

Nótese que $U^{-1} = U^{\operatorname{T}}$ y $R^{-1} = R^{\operatorname{T}}$ por la condición de ortogonalidad. Además, tenemos que $
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$ y por otro lado, $\boldsymbol{A} = \boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}$. Por la estructura de la ecuación, podemos interpretar a  $\boldsymbol{D}_{\sqrt{m}}$ como la matriz diagonal de $\boldsymbol{Y}$ y ahora veamos que, 

$$\boldsymbol{Y}^{\operatorname{T}}=\boldsymbol{U} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{R}^{\operatorname{T}}$$
$$\boldsymbol{A} = \boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y} = \boldsymbol{U} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{R}^{\operatorname{T}}\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}} = \boldsymbol{U}\boldsymbol{D}_{\sqrt{m}}^2\boldsymbol{U}^{\operatorname{T}} $$
$$\boldsymbol{A}=\boldsymbol{U}\boldsymbol{D}_{\sqrt{m}}^2\boldsymbol{U}^{\operatorname{T}}$$
Pero vimos que $\boldsymbol{Y_{diag}}=\boldsymbol{D}_{\sqrt{m}}$ por lo tanto, 
$$\boldsymbol{U}^{\operatorname{T}}\boldsymbol{A}\boldsymbol{U}=\boldsymbol{Y_{diag}}^2$$

Lo que quiere decir que $\boldsymbol{A_{diag}}=\boldsymbol{Y_{diag}}^2$