# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [75]:
# Librerias

import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

In [76]:
# Primero se determinan m1, m2 y m3

m1 = 10e-7 # Valor aleatorio para m1
delt_m_21 = 7.39e-5 
delt_m_32 = 2.449e-3


Para hallar $m_2$ hago uso de: \\
$\Delta m^2_{ij}=m^2_i-m^2_j$ \\

$\Delta m^2_{21}=m^2_2-m^2_1$ \\

$m_2 = \sqrt{\Delta m^2_{21} + m^2_1} $ \\

y para hallar $m_3$ \\

$\Delta m^2_{32}=m^2_3-m^2_2$ \\

$m_3 = \sqrt{\Delta m^2_{32} + m^2_2} $

In [77]:
m2 = np.sqrt(delt_m_21 + (m1)**2)
m2

0.008596510978298114

In [78]:
m3 = np.sqrt(delt_m_32 + (m2)**2)
m3

0.05022847798808958

In [79]:
# Determino la matriz U

theta_12 = 33.82*(np.pi/180) # radianes 
theta_23 = 48.3*(np.pi/180) # radianes 
theta_13 = 8.61*(np.pi/180) # radianes

c_12 = np.cos(theta_12)
c_23 = np.cos(theta_23)
c_13 = np.cos(theta_13)
s_12 = np.sin(theta_12)
s_23 = np.sin(theta_23)
s_13 = np.sin(theta_13)

$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$

In [80]:
U_11 = c_12*c_13
U_12 = s_12*c_13
U_13 = s_13
U_21 = -(s_12*c_23)-(c_12*s_13*s_23)
U_22 = (c_12*c_23)-(s_12*s_13*s_23)
U_23 = c_13*s_23
U_31 = (s_12*s_23)-(c_12*s_13*c_23)
U_32 = -(c_12*s_23)-(s_12*s_13*c_23)
U_33 = c_13*c_23

U = np.array ([[U_11, U_12, U_13],
              [U_21, U_22, U_23],
              [U_31, U_32, U_33]])
UT = np.transpose(U)

Para conseguir $Y$ debo obtener $\boldsymbol{D}_{\sqrt{m}}$  y $R$

In [81]:
# Obteniedno D_sqrt(m)

D_m = np.diag([np.sqrt(m1), np.sqrt(m2), np.sqrt(m3)])
D_m

array([[0.001     , 0.        , 0.        ],
       [0.        , 0.09271737, 0.        ],
       [0.        , 0.        , 0.22411711]])

In [82]:
# Obteniendo R

# Primero se toman valores arbitrarios para alpha

alfa_12 = np.pi/2 # radianes 
alfa_23 = np.pi # radianes 
alfa_13 = (3*np.pi)/2 # radianes

ca_12 = np.cos(alfa_12)
ca_23 = np.cos(alfa_23)
ca_13 = np.cos(alfa_13)
sa_12 = np.sin(alfa_12)
sa_23 = np.sin(alfa_23)
sa_13 = np.sin(alfa_13)

$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$

In [83]:
R_11 = ca_12*ca_13
R_12 = sa_12*ca_13
R_13 = sa_13
R_21 = -(sa_12*ca_23)-(ca_12*sa_13*sa_23)
R_22 = (ca_12*ca_23)-(sa_12*sa_13*sa_23)
R_23 = ca_13*sa_23
R_31 = (sa_12*sa_23)-(ca_12*sa_13*ca_23)
R_32 = -(ca_12*sa_23)-(sa_12*sa_13*ca_23)
R_33 = ca_13*ca_23

R = np.array ([[R_11, R_12, R_13],
              [R_21, R_22, R_23],
              [R_31, R_32, R_33]])

Con la información anterior se puede hallar $Y$
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


In [84]:
# Hallando Y

Y = R @ (D_m @ UT)
print('La matriz Y es:\n',Y)

La matriz Y es:
 [[-0.0335521  -0.16544858 -0.1474093 ]
 [ 0.00082143 -0.00046312  0.00033283]
 [-0.05102358 -0.04547352  0.06265193]]


Ahora se comprueba $A$ 
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$


In [85]:
A = (np.transpose(Y)) @ Y
A

array([[0.00372982, 0.00787099, 0.00174944],
       [0.00787099, 0.02944129, 0.0215395 ],
       [0.00174944, 0.0215395 , 0.02565488]])

In [86]:
av, avec = np.linalg.eig(A)

In [87]:
# Se comparan los autovalores 

print('autovalores de A: \n',av)
print('autovalores del inicio del ejercicio: \n',np.array([m1, m2, m3]))

autovalores de A: 
 [5.02284780e-02 1.00000000e-06 8.59651098e-03]
autovalores del inicio del ejercicio: 
 [1.00000000e-06 8.59651098e-03 5.02284780e-02]


In [88]:
# Se comparan los autovectores 

print('Autovectores de A:\n', avec)
print ('Autovectores U: \n',U)

Autovectores de A:
 [[-0.14970791 -0.82142745 -0.55031308]
 [-0.73822377  0.46312144 -0.49045305]
 [-0.65773339 -0.33282949  0.67573021]]
Autovectores U: 
 [[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]]


Salen los mismo terminos pero con signo contrario, no encuentro la razón.

In [67]:
# Ahora se comparan los autovalores de Y con la raiz cuadrada de los autovalores de A

np.linalg.eigvals(A)**0.5, np.linalg.eigvals(Y)

(array([0.22411711, 0.001     , 0.09271737]),
 array([ 0.11368479, -0.08284169, -0.0022064 ]))

In [70]:
av[0]**0.5-np.linalg.eigvals(Y)[0]

0.11043231318682106

In [72]:
av[1]**0.5-(-np.linalg.eigvals(Y)[2])

-0.001206402792214088

In [74]:
av[2]**0.5-(-np.linalg.eigvals(Y)[1])

0.009875683322653997

Las diferencias entre ambos valores son muy pequeñas, lo cual puede ser dado que no se tuvo en cuenta las incertidumbres de los valores iniciales en este ejercicio.