# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [ ]:
import numpy as np

In [ ]:
''' ============= Punto 1 ============= '''

m1 = np.random.uniform(-9, -4)
m1 = 10**m1

dm21 = 7.39*10**(-5)
m2 = np.sqrt(m1**2 + dm21)

dm32 = 2.449*10**(-3)
m3 = np.sqrt(dm32 + m2**2)

m1, m2, m3     # se cumple que las masas m1 < m2 < m3

(8.762068141886157e-05, 0.008596957449226577, 0.05022855440268824)

In [ ]:
''' ============= Punto 2 ============= '''

alpha12 = np.random.uniform(0, 2*np.pi)
alpha13 = np.random.uniform(0, 2*np.pi)
alpha23 = np.random.uniform(0, 2*np.pi)

alpha12, alpha13, alpha23

(3.1802400191996005, 1.3980451081047336, 2.215810099913796)

In [ ]:
''' ============= Punto 3 ============= '''

sin_12 = np.sin(alpha12)
sin_23 = np.sin(alpha23)
sin_13 = np.sin(alpha13)
cos_12 = np.cos(alpha12)
cos_13 = np.cos(alpha13)
cos_23 = np.cos(alpha23)

R = np.zeros([3, 3])    # Matriz ortogonal

R[0, 0] = cos_12*cos_13
R[0, 1] = sin_12*cos_13
R[0, 2] = sin_13
R[1, 0] = -sin_12*cos_23 - cos_12*sin_13*sin_23
R[1, 1] = cos_12*cos_23 - sin_12*sin_13*sin_23
R[1, 2] = cos_13*sin_23
R[2, 0] = sin_12*sin_23 - cos_12*sin_13*cos_23
R[2, 1] = -cos_12*sin_23 - sin_12*sin_13*cos_23
R[2, 2] = cos_13*cos_23
# -------------------------------------------------------------------

Dm = np.diag([m1**0.5, m2**0.5, m3**0.5])     # matriz diagonal

# ========== Matriz unitaria ==========
sin2_12 = 3.10*0.1
sin2_13 = 2.241*0.01
sin2_23 = 5.58*0.1

# Usamos la identidad trigonométrica cos**2(x) + sin**2(x) = 1
cos2_12 = 1 - sin2_12
cos2_13 = 1 - sin2_13
cos2_23 = 1 - sin2_23

# Eliminamos el cuadrados de los senos y cosenos
sin2_12 = sin2_12**0.5
sin2_13 = sin2_13**0.5
sin2_23 = sin2_23**0.5
cos2_12 = cos2_12**0.5
cos2_13 = cos2_13**0.5
cos2_23 = cos2_23**0.5

'''
theta_12 = 33.82*np.pi/180
theta_13 = 8.61*np.pi/180
theta_23 = 48.3*np.pi/180

sin2_12 = np.sin(theta_12)
sin2_13 = np.sin(theta_13)
sin2_23 = np.sin(theta_23)
cos2_12 = np.cos(theta_12)
cos2_13 = np.cos(theta_13)
cos2_23 = np.cos(theta_23)'''

U = np.zeros([3, 3])

U[0, 0] = cos2_12*cos2_13
U[0, 1] = sin2_12*cos2_13
U[0, 2] = sin2_13
U[1, 0] = -sin2_12*cos2_23 - cos2_12*sin2_13*sin2_23
U[1, 1] = cos2_12*cos2_23 - sin2_12*sin2_13*sin2_23
U[1, 2] = cos2_13*sin2_23
U[2, 0] = sin2_12*sin2_23 - cos2_12*sin2_13*cos2_23
U[2, 1] = -cos2_12*sin2_23 - sin2_12*sin2_13*cos2_23
U[2, 2] = cos2_13*cos2_23

# Y = R*Dm*Ut
Y = np.dot( np.dot(R, Dm), np.transpose(U) )
Y

array([[ 0.0313914 ,  0.16350673,  0.14500872],
       [ 0.04269397,  0.04810317, -0.01693912],
       [ 0.0313347 ,  0.02083003, -0.06577503]])

In [ ]:
''' ============= Punto 4 ============= '''

A = np.dot( np.transpose(Y), Y)     # Matriz generada

def argeig(a):
    """
    Diagonalize with increasing order in the eigenvalues.
  
    See help(np.linalg.eig)
    """
    l,V = np.linalg.eig(a)  #diagonalizacion 
    index = np.abs(l).argsort()
    argl = np.sort( l)
    argV = np.c_[ tuple([ np.c_[ V[:,i]] for i in index   ]) ]
    return argl, argV

l, v = argeig(A)

# veamos que U sea similar a v (matriz de vectores propios)
print('Matriz unitaria U:\n', U, '\n')
print('Matriz de vectores propios:\n', v, '\n')

print('\nMatriz diagonal:\n', np.diag([m1, m2, m3]), '\n')
print('Matriz diagonal de valores propios de A:\n', np.diag(l), '\n')

Matriz unitaria U:
 [[ 0.82130208  0.55050241  0.1496997 ]
 [-0.46305076  0.48998854  0.73857648]
 [ 0.33323699 -0.67591296  0.65733917]] 

Matriz de vectores propios:
 [[-0.82130208 -0.55050241 -0.1496997 ]
 [ 0.46305076 -0.48998854 -0.73857648]
 [-0.33323699  0.67591296 -0.65733917]] 


Matriz diagonal:
 [[8.76206814e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.59695745e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.02285544e-02]] 

Matriz diagonal de valores propios de A:
 [[8.76206814e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.59695745e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.02285544e-02]] 



In [ ]:
''' ============= Punto 5 ============= '''

ly, va = argeig(Y)

print('Raíz cuadrada de los valores propios de A:', l)
print('Valores propios de Y', ly**2)

print('\nDiferencia:', l - ly**2)

Raíz cuadrada de los valores propios de A: [8.76206814e-05 8.59695745e-03 5.02285544e-02]
Valores propios de Y [0.01160688 0.00017928 0.01818296]

Diferencia: [-0.01151926  0.00841768  0.0320456 ]


como $A=Y^TY$ entonces $diag(m_i)=UAU^T=UY^TYU^T=UY^TU^TUYU^T = diag(eigenvalues(Y^T))diag(eigenvalues(Y))=diag(eigenvalues(Y)^2)  $