## Parcial 3: Métodods Computacionales

### Gabriel Cataño Sánchez

#Enunciado

# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

# Solución

In [126]:
# Librerías
import numpy as np
from scipy import linalg as la
import matplotlib.pylab as plt
from scipy import optimize
from scipy.optimize import curve_fit
from scipy import integrate
from numpy import random

%pylab inline

Populating the interactive namespace from numpy and matplotlib


/usr/local/lib/python3.7/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['plt']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


## 1. Valores de m1,m2,m3

In [127]:
# Semilla para fijar el m
random.seed(4879)
m1 = np.random.uniform(1e-10,1e-4)
print(f'Valor m1 = {m1}  eV')

Valor m1 = 6.623918180048154e-05  eV


In [128]:
# Hallar los valores de m2 y m3 a paertir de m1

val1 = 7.39e-5       #eV^2
val2 = 2.449e-3      #eV^2
def deltm21(m1, v1):
  return np.sqrt(m1**2 + v1)

def deltm32(m2, v2):
  return np.sqrt(m2**2 + v2)


m2 = deltm21(m1,val1)
m3 = deltm32(m2,val2)
print(f'Valor m2 = {m2}  eV')
print(f'Valor m3 = {m3}  eV')

Valor m2 = 0.008596766114604118  eV
Valor m3 = 0.05022852165482482  eV


## 2. Hallar $\alpha_{ij}$

In [144]:
# Semilla para que los alpha no cambien

random.seed(2)
al = np.random.uniform(0,2*np.pi,3)
print(f'\u03B1_{12} = {round(np.rad2deg(al[0]),2)}°')
print(f'\u03B1_{13} = {round(np.rad2deg(al[1]),2)}°')
print(f'\u03B1_{23} = {round(np.rad2deg(al[2]),2)}°')

α_12 = 156.96°
α_13 = 9.33°
α_23 = 197.88°


## 3. Hallar R, $D_{\sqrt{m_i}}$ y Y

* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

In [130]:
# Definición de los cosenos y senos a partir de los alpha hallados

al12 = al[0]
al13 = al[1]
al23 = al[2]

c12 = np.cos(al12)
c13 = np.cos(al13)
c23 = np.cos(al23)
s12 = np.sin(al12)
s13 = np.sin(al13)
s23 = np.sin(al23)

x1 = np.array([c12*c13,s12*c13,s13])
x2 = np.array([-s12*c23-c12*s13*s23,c12*c23-s12*s13*s23,c13*s23])
x3 = np.array([s12*s23-c12*s13*c23,-c12*s23-s12*s13*c23,c13*c23])

# Matriz R

R = np.asmatrix([x1,x2,x3])
R

matrix([[-0.90803673,  0.38622144,  0.16217982],
        [ 0.32668528,  0.89526927, -0.30293508],
        [-0.26219463, -0.22209442, -0.93911024]])


where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$

In [131]:
# Definición de los valores de seno y coseno a partir de los theta entregados en la tabla

the12 = deg2rad(33.82)
the13 = deg2rad(8.61)
the23 = deg2rad(48.3)
c_12 = np.cos(the12)
c_13 = np.cos(the13)
c_23 = np.cos(the23)
s_12 = np.sin(the12)
s_13 = np.sin(the13)
s_23 = np.sin(the23)

x11 = np.array([c_12*c_13,s_12*c_13,s_13])
x21 = np.array([-s_12*c_23-c_12*s_13*s_23,c_12*c_23-s_12*s_13*s_23,c_13*s_23])
x31 = np.array([s_12*s_23-c_12*s_13*c_23,-c_12*s_23-s_12*s_13*c_23,c_13*c_23])

# Matriz U
U = np.asmatrix([x11,x21,x31])
U

matrix([[ 0.82142745,  0.55031308,  0.14970791],
        [-0.46312144,  0.49045305,  0.73822377],
        [ 0.33282949, -0.67573021,  0.65773339]])

In [132]:
# Raíz cuadrada de los valores de m1,m2 y m3
rm1 = np.sqrt(m1)
rm2 = np.sqrt(m2)
rm3 = np.sqrt(m3)

# Matriz diagonal con los valores de las raíces cuadradas de m1,m2 y m3
Drm = np.diag([rm1,rm2,rm3],0)
Drm

array([[0.00813875, 0.        , 0.        ],
       [0.        , 0.09271875, 0.        ],
       [0.        , 0.        , 0.22411721]])

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$

In [133]:
# Hallar Y a partir de R, la matriz diagonal y la transpuesta de U
Y = R@Drm@U.T
Y

matrix([[ 0.01907759,  0.04781814, -0.00275076],
        [ 0.03770043, -0.0106399 , -0.09986172],
        [-0.04459423, -0.16448581, -0.12522903]])

## 4. Hallar A

### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

In [134]:
# Hallar A a partir de Y y Y transpuesta
A = Y.T@Y
A

matrix([[0.00377392, 0.00784624, 0.00176719],
        [0.00784624, 0.02945536, 0.02152938],
        [0.00176719, 0.02152938, 0.02566224]])

In [135]:
# Valores y vectores propios de A
E1,V1 = la.eig(A)
E1

array([5.02285217e-02+0.j, 6.62391818e-05+0.j, 8.59676611e-03+0.j])

In [138]:
# Vemos que los valores propios de A son los valores de m1, m2 y m3
m1,m2,m3

(6.623918180048154e-05, 0.008596766114604118, 0.05022852165482482)

In [136]:
# Matriz de los vectores propios de A
V1

array([[-0.14970791, -0.82142745, -0.55031308],
       [-0.73822377,  0.46312144, -0.49045305],
       [-0.65773339, -0.33282949,  0.67573021]])

## 5. Autovalores y autovectores

In [137]:
# Valores y vectores propios de Y
E2, V2 = la.eig(Y)
E2

array([ 0.09886701+0.j, -0.0082474 +0.j, -0.20741095+0.j])

In [147]:
# Raíz caudrada de los autovalores de A
E1s = E1**.5
E1s

array([0.22411721+0.j, 0.00813875+0.j, 0.09271875+0.j])

In [157]:
# Diferencias entre los autovalores de la matriz Y y la raíz cuadrada de los autovalores de la matriz A
er1ay = abs(E2[0]) - E1s[2]
er2ay = abs(E2[1]) - E1s[1]
er3ay = abs(E2[2]) - E1s[0]
print(f'Error en las diferencias de los autovalores: \n {er1ay.round(),er2ay.round(), er3ay.round()}')

Error en las diferencias de los autovalores: 
 (0j, 0j, (-0+0j))


Observamos que el error hallado en las diferencia en el punto anterior es nulo, esto es, los autovalores de $\boldsymbol{Y}$, corresponden a la raíz cuadrada de los autovalores de $\boldsymbol{A}$. Esto se debe a que la matirz $\boldsymbol{Y}$, fue hallada multiplicando una matriz diagonal que contiene la raíz cuadrada de los valores de $m_1,m_2$ y $m_3$ en la diagonal, que a su vez corresponden a los autovalores de la matirz $\boldsymbol{A}$.