# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
 #librerias
 import numpy as np
 import sympy

In [2]:
#Punto 1
em1=np.random.uniform(-9,-4)# generando el exponente aleatorio 
m1= 10**(em1)#creando m1 del exponente aleatorio

dm21 = 7.39*(10**-5)
dm32 = 2.449*(10**-3)
#hallando a m2 y m3
m2 = np.sqrt(dm21+m1**2)
m3 = np.sqrt(dm32+m2**2)

print("m1 es: ",m1)
print("m2 es: ",m2)
print("m2 es: ",m3)

m1 es:  3.853795263625909e-06
m2 es:  0.008596511783958535
m2 es:  0.050228478125976875


In [3]:
#Punto 2
#generando 3 alpha aleatorios
a=np.random.uniform(0,2*np.pi,3)

print("los alpha son: ",a)

los alpha son:  [1.89156082 0.11772188 2.20071694]


In [4]:
#punto 3
#R por la def de arriba
#usando alpha
c12=np.cos(a[0])
c13=np.cos(a[1])
c23=np.cos(a[2])

s12=np.sin(a[0])
s13=np.sin(a[1])
s23=np.sin(a[2])
#R de la definicion de arriba
R=np.matrix([[c12*c13,s12*c13,s13],
             [-s12*c23-c12*s13*s23,c12*c23-s12*s13*s23,c13*s23],
             [s12*s23-c12*s13*c23,-c12*s23-s12*s13*c23,c13*c23]])
#D por la def de arriba
D=np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)])
#U por la definicion de arriba
t=np.array([33.82,8.61,48.3])#theta del cuadro
t=t*np.pi/180

c12=np.cos(t[0])
c13=np.cos(t[1])
c23=np.cos(t[2])

s12=np.sin(t[0])
s13=np.sin(t[1])
s23=np.sin(t[2])

U=np.matrix([[c12*c13,s12*c13,s13],
             [-s12*c23-c12*s13*s23,c12*c23-s12*s13*s23,c13*s23],
             [s12*s23-c12*s13*c23,-c12*s23-s12*s13*c23,c13*c23]])

#U transpuesta
Ut=np.transpose(U)

#Y por la def
Y=R*D*Ut

print("La matriz Y es: ")
sympy.Matrix(Y)

La matriz Y es: 


Matrix([
[  0.0515217701134123,  0.0625720763189395, -0.0419361717425409],
[  0.0327558302876305,   0.136584170592536,   0.112684452054737],
[-0.00207677225811892, -0.0828938995521931,  -0.105824223593449]])

In [5]:
#punto 4

Yt=np.transpose(Y) #transpuesta de Y
A=Yt*Y #A por definicion
values,vectors=np.linalg.eig(A) #eigenvectors y eigenvalues de A
#comprobacion de los eigenvalues
print("m1,m2,m3 \n", m1,m2,m3)#mostar m1,m2,m3
print("los valores propios de A son: \n", values,"\n")#valores propios de a
#comprobacion de los eigenvectors
print("los vectores propios de A son: \n", vectors,"\n")#vectores propios de a
print("matriz U \n", U)#u

m1,m2,m3 
 3.853795263625909e-06 0.008596511783958535 0.050228478125976875
los valores propios de A son: 
 [5.02284781e-02 3.85379526e-06 8.59651178e-03] 

los vectores propios de A son: 
 [[-0.14970791 -0.82142745 -0.55031308]
 [-0.73822377  0.46312144 -0.49045305]
 [-0.65773339 -0.33282949  0.67573021]] 

matriz U 
 [[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]]


In [6]:
#5
vy=np.linalg.eigvals(Y)
av=np.linalg.eigvals(A)**0.5
#np.sqrt(values)
print("raiz de los valores propios de A: \n", av)
print("autovalores de Y son: \n", vy)
b=np.array(sorted([np.linalg.eigvals(A)]))**0.5-np.array(sorted(np.linalg.eigvals(Y)))
print("La diferencia entre la raiz de los valores propios de A y Y es: ", b)


raiz de los valores propios de A: 
 [0.22411711 0.00196311 0.09271738]
autovalores de Y son: 
 [ 0.12874431 -0.00830333 -0.03815926]
La diferencia entre la raiz de los valores propios de A y Y es:  [[ 0.26227637  0.01026644 -0.03602693]]


In [7]:
#La diferencia deberia dar 0, esto no es posible puesto que hay errores experimentales

como $A=Y^TY$ entonces $diag(m_i)=UAU^T=UY^TYU^T=UY^TU^TUYU^T=diag(eigenvalues(Y^T))diag(eigenvalues(Y))=diag(eigenvalues(Y)^2)  $