In [1]:
import random
import numpy as np

#Se toma un número aleatorio como m1

m1 = np.random.uniform(10e-9, 10e-4)
m1

0.0005043243218578309

Se despeja la diferencia entre los valores m1, m2 y m3 para sacar los dos últimos.

$$\frac{\Delta m_{21}}{10^{-5}} = 7.39$$
$$\Delta m_{21}={10^{-5}}\times7.39$$

$$\frac{\Delta m_{32}}{10^{-3}} = 2.499$$
$$\Delta m_{21}={10^{-3}}\times2.499$$

In [2]:
Δm21 = np.sqrt(7.39 * 10e-5)
Δm32 = np.sqrt(2.449 * 10e-3)
m2 = np.sqrt(m1 ** 2 + Δm21 ** 2)
m3 = np.sqrt(m2 ** 2 + Δm32 ** 2)

Se sacan los $\alpha_{ij}$ aleatorios y se sacan senos y cosenos con cada uno de ellos. Luego, estos se usan para sacar la matriz R.
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$

In [3]:
α12 = np.random.uniform(0, 2 * np.pi)
α23 = np.random.uniform(0, 2 * np.pi)
α13 = np.random.uniform(0, 2 * np.pi)
s12_ = np.sin(α12)
s23_ = np.sin(α23)
s13_ = np.sin(α13)
c12_ = np.cos(α12)
c23_ = np.cos(α23)
c13_ = np.cos(α13)

In [4]:
R = np.array([[c12_ * c13_, s12_ * c13_, s13_],
             [-s12_ * c23_ - c12_ * s13_ * s23_, c12_ * c23_ - s12_ * s13_ * s23_, c13_ * s23_],
             [s12_ * s23_ - c12_ * s13_ * c23_, -c12_ * s23_ - s12_ * s13_ * c23_, c13_ * c23_]])
R

array([[-0.72508099, -0.39390052, -0.56488931],
       [-0.08401029, -0.76354941,  0.64026132],
       [-0.68352017,  0.51169783,  0.52054347]])

Se ponen los $\theta_{ij}$ como lo indica la tabla y estos se pasan a radianes para luego poderles sacar senos y cosenos a cada uno de ellos. Con esto sacamos la matriz U.
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$

In [5]:
θ12 = np.deg2rad(33.82)
θ23 = np.deg2rad(48.3)
θ13 = np.deg2rad(8.61)
c12 = np.cos(θ12)
s12 = np.sin(θ12)
c23 = np.cos(θ23)
s23 = np.sin(θ23)
c13 = np.cos(θ13)
s13 = np.sin(θ13)

In [6]:
U = np.array([[c12 * c13, s12 * c13, s13],
             [-s12 * c23 - c12 * s13 * s23, c12 * c23 - s12 * s13 * s23, c13 * s23],
             [s12 * s23 - c12 * s13 * c23, -c12 * s23 - s12 * s13 * c23, c13 * c23]])
U

array([[ 0.82142745,  0.55031308,  0.14970791],
       [-0.46312144,  0.49045305,  0.73822377],
       [ 0.33282949, -0.67573021,  0.65773339]])

Se saca la matriz $\boldsymbol{D}_{\sqrt{m}}$ al poner la raíz cuadrada de m1, m2 y m3 como una matriz diagonal. Luego se saca la matriz Y.
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$

In [7]:
D = np.diag([(m1), (m2), (m3)])
D

array([[0.00050432, 0.        , 0.        ],
       [0.        , 0.02718923, 0.        ],
       [0.        , 0.        , 0.15883719]])

In [8]:
Dsqrt = D ** 0.5
Dsqrt

array([[0.02245717, 0.        , 0.        ],
       [0.        , 0.16489158, 0.        ],
       [0.        , 0.        , 0.39854384]])

In [9]:
Y = R.dot(Dsqrt.dot(U.transpose()))
Y

array([[-0.08282305, -0.19051287, -0.10960787],
       [-0.03263443,  0.12749848,  0.25228372],
       [ 0.06488194,  0.20164215,  0.07432955]])

Se saca la matriz A 
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$
y a sus eigenvalores.

In [10]:
A = Y.transpose().dot(Y)
λ, V = np.linalg.eig(A)
λ_ = np.sort(λ)
λ_

array([0.00050432, 0.02718923, 0.15883719])

In [11]:
#se muestra que los lambda de A restados con los lambda original son, esencialmente, cero,
#mostrando que estos coinciden
print(λ_-[m1, m2, m3])  


[-5.96311195e-18 -2.08166817e-17  2.77555756e-17]


In [12]:
#Se muestra que los eigenvectores son los correctos al usar su definición A*Vi - lambda*Vi = 0

V0 = np.c_[ V[:, 0] ]
V1 = np.c_[ V[:, 1] ]
V2 = np.c_[ V[:, 2] ]
print(A.dot(V0) - λ[0]*V0, '\n')
print(A.dot(V1) - λ[1]*V1, '\n')
print(A.dot(V2) - λ[2]*V2)

[[-2.08166817e-17]
 [-1.38777878e-17]
 [-2.77555756e-17]] 

[[-3.84891771e-18]
 [-1.19533290e-17]
 [-1.71574994e-17]] 

[[-5.20417043e-18]
 [-8.67361738e-18]
 [ 1.04083409e-17]]


In [13]:
#Se sacan los eigenvalores de la matriz Y para mostrar que estos coinciden con la raíz cuadrada de los eigenvalores de A
λY = np.linalg.eigvals(Y)
λY_ = np.sort(λY)
λY_

array([-0.16853158, -0.02777231,  0.31530888])

In [14]:
print(λ_**0.5-λY_)

[0.19098874 0.19266389 0.08323497]


La matriz Y se describe con su diagonalización: $
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$, lo que nos indica que la matriz A es $\boldsymbol{A}=\boldsymbol{U}\boldsymbol{D}_{\sqrt{m}}^{\operatorname{T}} \boldsymbol{R}^{\operatorname{T}} \boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}$.

Como $\boldsymbol{R}^{\operatorname{T}} \boldsymbol{R} = I$, entonces llegamos a que $\boldsymbol{A}=\boldsymbol{U}\boldsymbol{D}_{\sqrt{m}}^{\operatorname{T}}  \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}$.

Que es lo mismo que decir $\boldsymbol{A}=\boldsymbol{U}\boldsymbol{D} \boldsymbol{U}^{\operatorname{T}}$, lo cual describe la diagonalización de A, siendo sus eigenvalores la diagonal de la matriz $\boldsymbol{D}$.