In [112]:
import numpy as np
import random

**Numeral 1**

In [113]:
# m1<m2<m3: Valor absoluto de los valores propios, Unidades: eV(Energía)
# Generar un valor aleatorio para m1, y con ello encontrar m2 y m3:

m1 = random.uniform(10E-9, 10E-4) #eV

#Fijandonos en la formula y en los valores que nos dan en la segunda columna de la "Data", y teniendo en cuenta los denominadores de la primera columna:
#Formula despejada: m_i^2 = bfp*10^n + m_j^2 

bfp_2 = 7.39*10**(-5) #bfp multiplicado por el valor del denominador de la primera columna
m2 = np.sqrt( bfp_2 + m1**2 )

bfp_3 = 2.449*10**(-3) #bfp multiplicado por el valor del denominador de la primera columna
m3 = np.sqrt( bfp_3 + m2**2 )

if m1<m2<m3:
  print("Valores propios [Energía]:\n",
        "\n",
      "m1:", m1 ,"eV\n",
      "m2:", m2 ,"eV\n",
      "m3:", m3 ,"eV\n")
else:
  print("No se cumple la condición inicial, debe haber un error")

Valores propios [Energía]:
 
 m1: 0.0003379589419132989 eV
 m2: 0.00860315152989991 eV
 m3: 0.05022961493229287 eV



**Numeral 2**

In [114]:
#Generando valores aleatorios para alpha_ij:

a_12 = random.uniform(0, 2*np.pi)

a_13 = random.uniform(0, 2*np.pi)

a_23 = random.uniform(0, 2*np.pi)

print("Valores de alpha [Radianes]: \n",
      "\n",
      "a_12:" , a_12, "\n",
      "a_13:" , a_13, "\n",
      "a_23:" , a_23)


Valores de alpha [Radianes]: 
 
 a_12: 0.5799666292395612 
 a_13: 1.648330050742668 
 a_23: 4.167128621910797


**Numeral 3**

In [115]:
#Ecuacion: Y = R*D+U^T

#Primero hallamos los s_ij y los c_ij , puesto que ya conocemos los theta(ángulos de mezcla) en la tabla "Data":
#Ecuaciones:
# s_ij = sin(theta)
# c_ij = cos(theta)

s_12 = np.sin(np.deg2rad(33.82))
c_12 = np.cos(np.deg2rad(33.82))

s_13 = np.sin(np.deg2rad(8.61))
c_13 = np.cos(np.deg2rad(8.61))

s_23 = np.sin(np.deg2rad(48.3))
c_23 = np.cos(np.deg2rad(48.3))

print("Valores de s_ij y c_ij:\n",
      "\n",
      "s_12:" , s_12 , "\n",
      "c_12:" , c_12 , "\n",
      "\n",
      "s_13:" , s_13 , "\n",
      "c_13:" , c_13 , "\n",
      "\n",
      "s_23:" , s_23 , "\n",
      "c_23:" , c_23 , "\n")

#Ahora que tenemos estos valores, debemos hallar U con la ecuación que se nos presenta:


U = np.array([[c_12*c_13, s_12*c_13, s_13],
              [-s_12*c_23-c_12*s_13*s_23, c_12*c_23-s_12*s_13*s_23, c_13*s_23],
              [s_12*s_23-c_12*s_13*c_23, -c_12*s_23-s_12*s_13*c_23, c_13*c_23]])

print("Matriz U:\n",
      "\n",
      U,"\n")

#La matriz D, ya está definida:

D = np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)])

print("Matriz D:\n",
      "\n",
      D,"\n")
#Ahora nos queda la matriz R, para ello primero hallamos los s^a_ij y c^a_ij:
#Ecuaciones:
#s^a_ij = sin(theta)
#c^a_ij = cos(theta)

sa_12 = np.sin(np.deg2rad(a_12))
ca_12 = np.cos(np.deg2rad(a_12))

sa_13 = np.sin(np.deg2rad(a_13))
ca_13 = np.cos(np.deg2rad(a_13))

sa_23 = np.sin(np.deg2rad(a_23))
ca_23 = np.cos(np.deg2rad(a_23))

print("Valores de sa_ij y ca_ij:\n",
      "\n",
      "sa_12:" , sa_12 , "\n",
      "ca_12:" , ca_12 , "\n",
      "\n",
      "sa_13:" , sa_13 , "\n",
      "ca_13:" , ca_13 , "\n",
      "\n",
      "sa_23:" , sa_23 , "\n",
      "ca_23:" , ca_23 , "\n")

#Matriz R:
R = np.array([[ca_12*ca_13, sa_12*ca_13, sa_13],
              [-sa_12*ca_23-ca_12*sa_13*sa_23, ca_12*ca_23-sa_12*sa_13*sa_23, ca_13*sa_23],
              [sa_12*sa_23-ca_12*sa_13*ca_23, -ca_12*sa_23-sa_12*sa_13*ca_23, ca_13*ca_23]])

print("Matriz R:\n",
      "\n",
      R,"\n")

#Así ya podemos hallar Y:

Y =  R @ (D @ U.transpose())

print("\033[91m"+"Matriz Y:"+"\033[0m", "\n",
      "\n",
      Y,"\n")



Valores de s_ij y c_ij:
 
 s_12: 0.556585649903383 
 c_12: 0.8307902348497055 
 
 s_13: 0.14970791170877362 
 c_13: 0.9887302671466056 
 
 s_23: 0.7466381822853914 
 c_23: 0.6652303546543609 

Matriz U:
 
 [[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]] 

Matriz D:
 
 [[0.01838366 0.         0.        ]
 [0.         0.09275318 0.        ]
 [0.         0.         0.22411964]] 

Valores de sa_ij y ca_ij:
 
 sa_12: 0.01012215437465602 
 ca_12: 0.9999487696831352 
 
 sa_13: 0.02876481832806117 
 ca_13: 0.9995862070009538 
 
 sa_23: 0.07266601205002668 
 ca_23: 0.9973563308530935 

Matriz R:
 
 [[ 0.999535    0.01011797  0.02876482]
 [-0.01218551  0.99728408  0.07263594]
 [-0.02795177 -0.07295268  0.99694363]] 

Matriz Y: 
 
 [[ 0.01657541 -0.00329048  0.00972187]
 [ 0.05315776  0.05748892 -0.05187312]
 [ 0.0293041   0.16186405  0.1513618 ]] 



**Numeral 4**

In [116]:
#Primero debemos calcular A:
#Ecuación: A = YT*Y

A = Y.transpose() @ Y

print("Matriz A:\n",
      "\n",
      A,"\n")

#Autovalores y autovectores:

A_valor, A_vector = np.linalg.eig(A)

#Para ver si se cumplen los valores propios calulemos: UT*A*U, y debería dar una matriz diagonal con los valores propios en la diagonal:

K = U.transpose() @ A @U

print("Matriz K:\n",
      "\n",
     K,"\n")

Matriz A:
 
 [[0.00395922 0.00774472 0.00183921]
 [0.00774472 0.02951578 0.02148591]
 [0.00183921 0.02148591 0.02569573]] 

Matriz K:
 
 [[ 3.37958942e-04 -4.20646714e-19  3.79041103e-19]
 [-4.22982274e-19  8.60315153e-03 -2.30376669e-18]
 [-6.66715321e-19  1.36590248e-19  5.02296149e-02]] 



**Vemos que nos da una matriz diagonal (los otros valores son ceros numericos), y los valores de la diagonal coinciden con m1,m2,m3.**

In [117]:
#Los valores propios también los puedo ver con A_valor:
M = np.array([m1,m2,m3]) # Array con los valores de m_i
print("Valores propios de A:\n",
      A_valor,"\n")
print("Valores m_i:\n",
      M,"\n")
#Para los vectores propios:
print("Vetores propios de A:\n",
      A_vector,"\n")
print("Matriz U:\n",
      U,"\n")

Valores propios de A:
 [0.05022961 0.00033796 0.00860315] 

Valores m_i:
 [0.00033796 0.00860315 0.05022961] 

Vetores propios de A:
 [[-0.14970791 -0.82142745 -0.55031308]
 [-0.73822377  0.46312144 -0.49045305]
 [-0.65773339 -0.33282949  0.67573021]] 

Matriz U:
 [[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]] 



**Vemos que los vectores columna de U coinciden con los vectores propios obtenidos (con signo contrario :( ),**
**Además acá se comprueban los valores propios de otra forma diferente a la anterior**

**Numeral 5**
**En este numeral no me dió esa corresponencia entre los valores propios**

In [132]:
Y_valor, Y_vector = np.linalg.eig(Y)
print(Y_valor)

[0.02465572+0.j         0.1003852 +0.07363764j 0.1003852 -0.07363764j]
