# Casas-Ibarra
Let $\boldsymbol{A}$ $3\times3$ a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [ ]:
# Bibliotecas.
import numpy as np
import random
import scipy.linalg as la

#1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.

In [ ]:
h = (random.randint(4, 9))
m1 = 10**(-h)
print('m1 = {}'.format(m1))

m1 = 1e-05


where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.

Para $m_2$:

$\dfrac{\Delta m^2_{21}}{10^{-5}} = 7.39$


$\Delta m^2_{21} = (7.39)(10^{-5}) = m^2_2 - m^2_1$

$m_2 = \sqrt{(7.39)(10^{-5})+m^2_1}$

In [ ]:
m2 = np.sqrt((7.39*1E-5)+m1)
print('m2 = {}'.format(m2))

m2 = 0.00915969431804359


Para $m_3$:

$\dfrac{\Delta m^2_{32}}{10^{-3}} = 2.449$

$\Delta m^2_{32} = (2.449)(10^{-3}) = m^2_3 - m^2_2$

$m_3 = \sqrt{(2.449)(10^{-3})+m^2_2}$

In [ ]:
m3 = np.sqrt((2.449*1E-3)+m2)
print('m3 = {}'.format(m3))

m3 = 0.10774365094075655


#2. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$


In [ ]:
α12= random.uniform(0, np.pi*2)
α13 = random.uniform(0, np.pi*2)
α23 = random.uniform(0, np.pi*2)

print('Los valores de α son:\nα12 = {}\nα13 = {}\nα23 = {}'.format(α12,α13,α23))

Los valores de α son:
α12 = 1.9345285220181176
α13 = 3.6847188278651295
α23 = 6.2099806774320285


#3. Obtain $\boldsymbol{Y}$
The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$

### Valores de $\theta$

In [ ]:
#Theta 
θ12 = np.deg2rad(33.82)
θ23 = np.deg2rad(48.30)
θ13 = np.deg2rad(8.61)

### Matriz R

In [ ]:
#Matriz R
def C(x):
  return np.cos(x)

def S(x):
  return np.sin(x)  

R1 = np.array([C(α12)*C(α13), S(α12)*C(α13), S(α13)])
R2 = np.array([-S(α12)*C(α23)-C(α12)*S(α13)*S(α23), C(α12)*C(α23)-S(α12)*S(α13)*S(α23), C(α13)*S(α23)])
R3 = np.array([S(α12)*S(α23)-C(α12)*S(α13)*C(α23), -C(α12)*S(α23)-S(α12)*S(α13)*C(α23), C(α13)*C(α23)])
R = np.asmatrix([R1,R2,R3])
R

matrix([[ 0.30456919, -0.80008753, -0.51681482],
        [-0.9186248 , -0.39013834,  0.06261432],
        [-0.25172621,  0.45568852, -0.85380436]])

matriz $\boldsymbol{D}_{\sqrt{m}}$

$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$

In [ ]:
f = lambda t : np.sqrt(t)
fv = np.vectorize(f)
ms = [m1,m2,m3]
Dsqrt = np.diag(fv(ms),0)
Dsqrt

array([[0.00316228, 0.        , 0.        ],
       [0.        , 0.09570629, 0.        ],
       [0.        , 0.        , 0.32824328]])

## Matriz U

In [ ]:
U1 = np.array([C(θ12)*C(θ13), S(θ12)*C(θ13), S(θ13)])
U2 = np.array([-S(θ12)*C(θ23)-C(θ12)*S(θ13)*S(θ23), C(θ12)*C(θ23)-S(θ12)*S(θ13)*S(θ23), C(θ13)*S(θ23)])
U3 = np.array([S(θ12)*S(θ23)-C(θ12)*S(θ13)*C(θ23), -C(θ12)*S(θ23)-S(θ12)*S(θ13)*C(θ23), C(θ13)*C(θ23)])
U = np.asmatrix([U1,U2,U3])
U

matrix([[ 0.82142745,  0.55031308,  0.14970791],
        [-0.46312144,  0.49045305,  0.73822377],
        [ 0.33282949, -0.67573021,  0.65773339]])

## Matriz $U^T$

In [ ]:
UT = np.transpose(U)
UT

matrix([[ 0.82142745, -0.46312144,  0.33282949],
        [ 0.55031308,  0.49045305, -0.67573021],
        [ 0.14970791,  0.73822377,  0.65773339]])

## Matriz Y

$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$

In [ ]:
Y = R@(Dsqrt@UT)
Y

matrix([[-0.0667448 , -0.16323472, -0.05951502],
        [-0.01985727, -0.00179502,  0.03778225],
        [-0.01860996, -0.18513288, -0.21406849]])

# 4. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors

## Matriz $\boldsymbol{A}$ a partir de $\boldsymbol{Y}$

$
\boldsymbol{A}=\boldsymbol{Y}^T\boldsymbol{Y}
$

In [ ]:
YT = np.transpose(Y)
A = YT@Y
A

matrix([[0.00519551, 0.01437603, 0.00720587],
        [0.01437603, 0.06092298, 0.04927821],
        [0.00720587, 0.04927821, 0.05079485]])

## Vectores(VecA) y valores(ValA) propios de A

In [ ]:
ValA, VecA = np.linalg.eig(A)
print('Valores propios de A a partir de Y:\n {}\n '.format(ValA))
print('Vectores propios de A a partir de Y:\n {}'.format(VecA))

Valores propios de A a partir de Y:
 [1.07743651e-01 1.00000000e-05 9.15969432e-03]
 
Vectores propios de A a partir de Y:
 [[-0.14970791 -0.82142745 -0.55031308]
 [-0.73822377  0.46312144 -0.49045305]
 [-0.65773339 -0.33282949  0.67573021]]



$\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}$

$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$

In [ ]:
UA = UT@(A@U)
UA

matrix([[ 1.00000000e-05, -6.51483348e-21,  5.41620958e-18],
        [-2.79378661e-18,  9.15969432e-03,  1.50113795e-18],
        [ 2.82151605e-18,  1.15571054e-18,  1.07743651e-01]])

##### Como se puede observar los valores propios $m_1,m_2,m_3$ Estan en la diagonal del producto $\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}$, los demas valores de la matriz son despreciables(tomados como 0) pues son de orden de magnitud -18 o -21.

Valores propios usando $\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}$

In [ ]:
ValUA = [UA[0,0], UA[1,1], UA[2,2]]
ValUA

[1.0000000000001517e-05, 0.009159694318043591, 0.10774365094075658]

Valores porpios usando
$\boldsymbol{A}=\boldsymbol{Y}^T\boldsymbol{Y}$

In [ ]:
sorted(list(ValA))

[1.000000000000364e-05, 0.009159694318043591, 0.10774365094075665]

Valores propios tomados tomados $m_1,m_2,m_3$

In [ ]:
[m1,m2,m3]

[1e-05, 0.00915969431804359, 0.10774365094075655]

Se puede concluir que los valores propios son los mismos, por consiguiente los vectores propios seran iguales.

#5.Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

## Valores propios de  $\boldsymbol{Y}$

In [ ]:
ValY, VecY = np.linalg.eig(Y)
print('Valores propios de Y:\n {}\n '.format(ValY))
print('Vectores propios de Y:\n {}'.format(VecY))


Valores propios de Y:
 [ 0.00524318 -0.10188327 -0.18596822]
 
Vectores propios de Y:
 [[-0.81021755  0.55981901  0.24452473]
 [ 0.47997006  0.38754116 -0.1694909 ]
 [-0.33641679 -0.73240325  0.95471488]]


In [ ]:
m = np.array([m1,m2,m3])
m = fv(m)
m

array([0.00316228, 0.09570629, 0.32824328])

In [ ]:
UT@(YT@(Y@U))

matrix([[ 1.00000000e-05,  1.14953047e-18, -1.52268432e-18],
        [ 1.02375547e-18,  9.15969432e-03,  8.44003186e-18],
        [ 1.48519279e-18,  2.59356505e-18,  1.07743651e-01]])

$D_A^{1/2}-D_y$

In [ ]:
m-ValY

array([-0.0020809 ,  0.19758956,  0.5142115 ])

### La diferencia no es 0

### En este caso las raiz cuadrada de los autovalores de $\boldsymbol{A}$ no corresponden con los autovalores de $\boldsymbol{Y}$, para encontar una razon primero veamos que es $\boldsymbol{U}^{\operatorname{T}}\boldsymbol{U}$ y $\boldsymbol{U}\boldsymbol{U}^{\operatorname{T}}$

In [ ]:
np.transpose(U)@U

matrix([[ 1.00000000e+00, -6.17198363e-17,  2.93663603e-17],
        [-6.17198363e-17,  1.00000000e+00, -2.66191823e-17],
        [ 2.93663603e-17, -2.66191823e-17,  1.00000000e+00]])

In [ ]:
U@np.transpose(U)

matrix([[ 1.00000000e+00, -3.86035020e-17,  3.59993582e-17],
        [-3.86035020e-17,  1.00000000e+00, -1.71207185e-17],
        [ 3.59993582e-17, -1.71207185e-17,  1.00000000e+00]])

### Podemos ver que $\boldsymbol{U}^{\operatorname{T}}\boldsymbol{U}$ y $\boldsymbol{U}\boldsymbol{U}^{\operatorname{T}}$ nos da como resultado 1 en la diagonal y numeros del orden de -17 en el resto de los valores es decir $\boldsymbol{U}^{\operatorname{T}}\boldsymbol{U} = \boldsymbol{I} $,$\boldsymbol{U}\boldsymbol{U}^{\operatorname{T}} = \boldsymbol{I} $ ahora:

$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix},\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=D_A
$$

$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

$$D_A = \boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U} = \boldsymbol{U}^T \boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y} \boldsymbol{U} = \boldsymbol{U}^T \boldsymbol{Y}^{\operatorname{T}}\boldsymbol{I}\boldsymbol{Y} \boldsymbol{U}=\boldsymbol{U}^T \boldsymbol{Y}^{\operatorname{T}}\boldsymbol{U}\boldsymbol{U}^{\operatorname{T}}\boldsymbol{Y} \boldsymbol{U} = D_{Y^T}D_{Y}$$

Y dado que los valores propios de una matriz y su transpuesta son iguales entonces:

$$D_{Y^T}=D_{Y}$$

Es decir:

$$D_A = D_y^2$$ 

Muy posiblemente en el ejemplo los valores no den exactamente igual por error y aproximaciones de la maquina.

