# Casas-Ibarra Parametrisation
## Juan David Salcedo Hernández
Let $\boldsymbol{A}$ be a $3 \times 3$ symmetric, non-diagonal matrix with the following set of eigenvalues and eigenvectors:


____

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which just of an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The unitary matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.


### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [1]:
import numpy as np

We shall use the fact that
\begin{equation}
{\Delta m_{2,1}}^2 := {m_2}^2 - {m_1}^2 = 7.39 \times 10^{-5}\text{ eV}^2,
\end{equation}
while
\begin{equation}
{\Delta m_{3,2}}^2 := {m_3}^2 - {m_2}^2 = 2.449 \times 10^{-3}\text{ eV}^2.
\end{equation}

In [181]:
# To begin with, we choose an arbitrary value in the desired range
m_1 = np.exp( np.random.uniform(np.log(1e-9), np.log(1e-4)) )

In [182]:
# The following m values arise from the ones listed in the table:
m_2 = np.sqrt(m_1**2 + 7.39e-5)
m_3 = np.sqrt(m_2**2 + 2.449e-3)

# The problem amounts to finding a symmetric matrix whose eigenvalues are 
# precisely these m values, oredered as follows:
eigvals = np.array([m_1, m_2, m_3])
ordered_eigvals = np.sort(eigvals)
ordered_eigvals

array([2.85615487e-07, 8.59651092e-03, 5.02284780e-02])

In [183]:
def rotation_operator(angle_12, angle_13, angle_23,
                      eigenvalues=None, reordering=False):
    ''' returns a rotation matrix, ignoring any complex phase '''

    s_12 = np.sin(angle_12)
    s_13 = np.sin(angle_13)
    s_23 = np.sin(angle_23)

    c_12 = np.cos(angle_12)
    c_13 = np.cos(angle_13)
    c_23 = np.cos(angle_23)

    A = np.array([[1,0,0],
                  [0,c_23,s_23],
                  [0,-s_23,c_23]])
    B = np.array([[c_13,0,s_13],
                  [0,1,0],
                  [-s_13,0,c_13]])
    C = np.array([[c_12,s_12,0],
                  [-s_12,c_12,0],
                  [0,0,1]])
    
    if reordering:
        ordered_columns = np.asarray(eigenvalues).argsort()
        return ((A @ B @ C).T[ordered_columns]).T
    else:
        return A @ B @ C

In [184]:
# Now we choose random mixing angles, which we use to define the matrix R
alpha_12, alpha_13, alpha_23 = tuple(
    *np.random.uniform(0, 2*np.pi, size=(1,3)))

In [185]:
R = rotation_operator(alpha_12, alpha_13, alpha_23)# ,eigenvalues=eigvals, reordering=True)
R

array([[-0.17239137,  0.18592263,  0.96732311],
       [ 0.4212588 , -0.87377556,  0.24301707],
       [ 0.89040566,  0.44938742,  0.07230982]])

We use the values in the table to define the $U$ operator.

In [186]:
theta_12 = np.deg2rad(33.82)
theta_13 = np.deg2rad(8.61)
theta_23 = np.deg2rad(14.3)

U = rotation_operator(theta_12, theta_13, theta_23)#, eigenvalues=eigvals, reordering=True)
U

array([[ 0.82142745,  0.55031308,  0.14970791],
       [-0.57006097,  0.78446755,  0.2442154 ],
       [ 0.01695393, -0.28594787,  0.95809518]])

In [192]:
# Finally, we get Y
Y = R @ np.diag(np.sqrt(ordered_eigvals)) @ U.T
Y

array([[ 0.04186648,  0.06651972,  0.20277815],
       [-0.03624449, -0.05038031,  0.07535161],
       [ 0.02574639,  0.03637209,  0.00362052]])

In [199]:
# Likewise, we can get A
A = Y.T @ Y
A_eigvals, A_eigvecs = np.linalg.eig(A)
A

array([[0.00372934, 0.00554741, 0.00585174],
       [0.00554741, 0.00828598, 0.00982419],
       [0.00585174, 0.00982419, 0.04680995]])

Notice that the eigenvalues of A are indeed the ones that we had arbitrarily selected:

In [194]:
np.sort(A_eigvals), ordered_eigvals

(array([2.85615487e-07, 8.59651092e-03, 5.02284780e-02]),
 array([2.85615487e-07, 8.59651092e-03, 5.02284780e-02]))

Likewise, the eigenvectors of $A$ are all in the span of the basis formed by the columns of $U$, as expected. By way of explanation, the columns of the first matrix can be written as the negative of another column in the second matrix.

In [190]:
A_eigvecs, U

(array([[-0.14970791, -0.82142745, -0.55031308],
        [-0.2442154 ,  0.57006097, -0.78446755],
        [-0.95809518, -0.01695393,  0.28594787]]),
 array([[ 0.82142745,  0.55031308,  0.14970791],
        [-0.57006097,  0.78446755,  0.2442154 ],
        [ 0.01695393, -0.28594787,  0.95809518]]))

Not surprisingly, the eigenvalues of the matrix $A^{T}A$ correspond to the squares of the eigenvalues of $A$. This is to say that $A$ is a *normal operator*, viz., there exists an *isometry* (a distance-preserving transformation, in this case, a rotation) such that
\begin{equation}
A_{\text{diag}} = U A U^{-1}.
\end{equation}
Such matrices satisfy the aforementioned property. Furthermore, they commute with their adjoint, which in the case of real matrices means that $A^{T}A = AA^{T}$.

In [197]:
ATA_eigvals, ATA_eigvecs = np.linalg.eig(A.T @ A)
np.sqrt(ATA_eigvals), A_eigvals

(array([5.02284780e-02, 2.85615430e-07, 8.59651092e-03]),
 array([5.02284780e-02, 2.85615487e-07, 8.59651092e-03]))

Nevertheless, the same cannot be said about the eigenvalues of $Y$ and the square root of the eigenvalues of $A$:

In [198]:
Y_eigvals, Y_eigvecs = np.linalg.eig(Y)
Y_eigvals, np.sqrt(A_eigvals)

(array([-0.08946652,  0.08601628, -0.00144306]),
 array([0.22411711, 0.00053443, 0.09271737]))

In [28]:
# Ignore this
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
(A.T[[0,2,1]]).T

array([[1, 3, 2],
       [4, 6, 5],
       [7, 9, 8]])