**Valentina Duarte Cardona**
**CC:1000319349**

# Casas-Ibarra

Let  A   3×3  a symmetric non-diagonal matrix with the following set of eigenvalues and eigenvectors:

### Eigenvalues
The normal ordering of the absolute value of the eigenvalues is $m_1<m_2<m_3$. Each eigenvalue is expressed in units of eV, which is just an energy unit.
### Eigenvectors
The eigenvectors in the normal ordering are defined by
$$
\boldsymbol{U}^T \boldsymbol{A} \boldsymbol{U}=
\begin{pmatrix}
m_1& 0 & 0\\
0 & m_2& 0\\
0 & 0 & m_3\\
\end{pmatrix}.
$$
The orthogonal matrix can be parameterized in terms of three mixing angles, $\theta_{23}$ $\theta_{13}$, $\theta_{12}$, such that
$$
\boldsymbol{U}=\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & c_{23} & s_{23} \\
0 & -s_{23} & c_{23}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{13} & 0 & s_{13}  \\
0 & 1 & 0 \\
-s_{13}  & 0 & c_{13}
\end{array}\right) \cdot\left(\begin{array}{ccc}
c_{12} & s_{12} & 0 \\
-s_{12} & c_{12} & 0 \\
0 & 0 & 1
\end{array}\right),
$$
where $c_{i j} \equiv \cos \theta_{i j}$ and $s_{i j} \equiv \sin \theta_{i j}$. Thus, we can write $\boldsymbol{U}$ as
$$
\boldsymbol{U}=\left(\begin{array}{ccc}c_{12} c_{13} & s_{12} c_{13} & s_{13}  \\ -s_{12} c_{23}-c_{12} s_{13} s_{23}& c_{12} c_{23}-s_{12} s_{13} s_{23}  & c_{13} s_{23} \\ s_{12} s_{23}-c_{12} s_{13} c_{23} & -c_{12} s_{23}-s_{12} s_{13} c_{23}  & c_{13} c_{23}\end{array}\right)
$$
so that
$$
\boldsymbol{U}_1=\begin{pmatrix}U_{e1}\\ U_{\mu 1}\\ U_{\tau 1}\end{pmatrix}=\begin{pmatrix}
c_{12} c_{13} \\
-s_{12} c_{23}-c_{12} s_{13} s_{23}  \\
s_{12} s_{23}-c_{12} s_{13} c_{23} 
\end{pmatrix},\qquad 
\boldsymbol{U}_2=\begin{pmatrix}U_{e2}\\ U_{\mu 2}\\ U_{\tau 2}\end{pmatrix}=\begin{pmatrix}
s_{12} c_{13} \\
c_{12} c_{23}-s_{12} s_{13} s_{23}  \\
-c_{12} s_{23}-s_{12} s_{13} c_{23} 
\end{pmatrix},\qquad
\boldsymbol{U}_3=\begin{pmatrix}U_{e3}\\ U_{\mu 3}\\ U_{\tau 3}\end{pmatrix}=\begin{pmatrix}
s_{13}  \\
c_{13} s_{23} \\
c_{13} c_{23}
\end{pmatrix}
$$

### Data
Use the _central values_  of the following table but ignoring $\delta_{CP}$ (In the previous equations was fixed to $\delta_{CP}=0$). __Hint__: take care of the denominator in the first colum.

![IMAGE](https://github.com/restrepo/ComputationalMethods/raw/master/material/figures/nu.png)

where $\Delta m^2_{ij}=m^2_i-m^2_j$ is the squared mass difference between eigenvalues $i$ and $j$; in units of $\text{eV}^2$.

### Casas-Ibarra parameterization
We can assumme without lost of generality that $\boldsymbol{A}$ can be generated from a matrix $\boldsymbol{Y}$ such that
$$
\boldsymbol{A}=\boldsymbol{Y}^{\operatorname{T}}\boldsymbol{Y}
$$

The matrix $\boldsymbol{Y}$ can be parameterized in terms of an arbitray orthogonal $3\times 3$ matrix, $\boldsymbol{R}$, as
$$
\boldsymbol{Y}=\boldsymbol{R} \boldsymbol{D}_{\sqrt{m}} \boldsymbol{U}^{\operatorname{T}}
$$


* $R$ is an orthogonal $3\times 3$ matrix, with three rotation angles $\alpha_{ij}$ between $(0,2\pi)$
$$
\boldsymbol{R}=\left(\begin{array}{ccc}c^\alpha_{12} c^\alpha_{13} & s^\alpha_{12} c^\alpha_{13} & s^\alpha_{13}  \\ -s^\alpha_{12} c^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} s^\alpha_{23}& c^\alpha_{12} c^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} s^\alpha_{23}  & c^\alpha_{13} s^\alpha_{23} \\ s^\alpha_{12} s^\alpha_{23}-c^\alpha_{12} s^\alpha_{13} c^\alpha_{23} & -c^\alpha_{12} s^\alpha_{23}-s^\alpha_{12} s^\alpha_{13} c^\alpha_{23}  & c^\alpha_{13} c^\alpha_{23}\end{array}\right)
$$
where $c^\alpha_{i j} \equiv \cos \alpha_{i j}$ and $s^\alpha_{i j} \equiv \sin \alpha_{i j}$.

* $$
 \boldsymbol{D}_{\sqrt{m}}=\operatorname{diag}\left(\sqrt{m_1},\sqrt{m_2},\sqrt{m_3}\right)
$$

### Problem
1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.
1. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$
1. Obtain $\boldsymbol{Y}$
1. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors
1. Check that the eigenvalues of $\boldsymbol{Y}$ correspond to the square root of the eigenvalues of $\boldsymbol{A}$ and explain why.

In [2]:
#importando librerias
import numpy as np
import random as rd

1. Choose a random value for $m_1$ between $10^{-9}\ \text{eV}$ and $10^{-4}\ \text{eV}$. Note that because of the wide range, the random variation  must be in the exponents. Obtain the corresponding $m_2$ and $m_3$ with the proper normal ordering.

In [3]:
# [eV] 
m1 = (10 ** rd.randint(-9, -4)) #Se escoge m1 aleatoriamente
m2 = np.sqrt(7.39 * (10**(-5)) + m1 ** 2) #Se escoge m2 a partir de la información dada en la tabla
m3 = np.sqrt(2.449 * (10**(-3)) + m2 ** 2) #Se escoge m3 a partir de la información dada en la tabla

print("m1:{}, m2:{}, m3:{}".format(m1,m2,m3))

m1:1e-08, m2:0.008596510920140799, m3:0.050228477978136066


2. Choose random values for $\alpha_{ij}$  between $(0,2\pi)$

In [4]:
alpha12 = rd.uniform(0, 2 * np.pi) #Se escoge un alpha12 aleatorio entre 0 y 2pi
alpha13 = rd.uniform(0, 2 * np.pi) #Se escoge un alpha13 aleatorio entre 0 y 2pi
alpha23 = rd.uniform(0, 2 * np.pi) #Se escoge un alpha23 aleatorio entre 0 y 2pi

print("alpha12:{}, alpha13:{}, alpha23:{}".format(alpha12, alpha13, alpha23))

alpha12:3.4724482826650243, alpha13:3.0320117318052047, alpha23:3.027384542691986


3. Obtain $\boldsymbol{Y}$

In [7]:
#thetaij en radianes
theta12 = np.deg2rad(33.82) #Se genera theta12 a partir de la información dada 
theta13 = np.deg2rad(8.61)  #Se genera theta13 a partir de la información dada
theta23 = np.deg2rad(48.3)  #Se genera theta23 a partir de la información dada

#Valores correspondientes a la matriz U 
cos12 = np.cos(theta12) 
cos13 = np.cos(theta13)
cos23 = np.cos(theta23)

sin12 = np.sin(theta12)
sin13 = np.sin(theta13)
sin23 = np.sin(theta23)

#Se generan la matrices que daran origen a la matriz U
U1 = np.matrix([[1, 0,  0],
                [0,cos23,sin23],
                [0,-sin23,cos23]])

U2 = np.matrix([[cos13, 0,  sin13],
                [0,    1,   0],
                [-sin13, 0, cos13]])

U3 = np.matrix([[cos12, sin12,  0],
                [-sin12, cos12,  0],
                [0,     0,  1]])

#Se genera la matriz U
U = U1 * U2 * U3 
#La transpuesta de la matriz U
Ut =np.transpose(U) 

print("U:{}".format(U))
print("Ut:{}".format(Ut))


U:[[ 0.82142745  0.55031308  0.14970791]
 [-0.46312144  0.49045305  0.73822377]
 [ 0.33282949 -0.67573021  0.65773339]]
Ut:[[ 0.82142745 -0.46312144  0.33282949]
 [ 0.55031308  0.49045305 -0.67573021]
 [ 0.14970791  0.73822377  0.65773339]]


In [9]:
#Se genera la matriz diagonal con los autovalores de A
D = np.diag([np.sqrt(m1),np.sqrt(m2),np.sqrt(m3)]) 

#Se generan los valores correspondientes a la matriz R
c12 = np.cos(alpha12)
c13 = np.cos(alpha13)
c23 = np.cos(alpha23)

s12 = np.sin(alpha12)
s13 = np.sin(alpha13)
s23 = np.sin(alpha23)


R11, R12, R13 = c12 * c13 , s12 * c13, s13
R21, R22, R23= -s12 * c23 - c12 * s13 * s23, c12 * c23 - s12 * s13 * s23, c13 * s23
R31, R32, R33 = s12 * s23 - c12 * s13 * c23, -c12 * s23 - s12 * s13 * c23, c13 * c23 

#Matriz R ortogonal 3x3 con rotacion de ángulos alphaij
R = np.array([[R11, R12, R13],
             [R21, R22, R23],
             [R31, R32, R33]])

print(R)

[[ 0.94009206  0.32290391  0.10936175]
 [-0.31094913  0.94365199 -0.11327646]
 [-0.13977684  0.07248436  0.98752643]]


In [13]:
#Se genera la matriz Y 
Y = R * D * Ut
#La transpuesta de la matriz Y
Yt = np.transpose(Y) 

print("Y:{}".format(Y))
print("Yt:{}".format(Yt))

Y:[[ 7.72217420e-05 -4.35376790e-05  3.12890362e-05]
 [ 4.81485047e-02  4.29111754e-02 -5.91216176e-02]
 [ 3.31335897e-02  1.63384842e-01  1.45570584e-01]]
Yt:[[ 7.72217420e-05  4.81485047e-02  3.31335897e-02]
 [-4.35376790e-05  4.29111754e-02  1.63384842e-01]
 [ 3.12890362e-05 -5.91216176e-02  1.45570584e-01]]


4. Check that the generated $\boldsymbol{A}$ has the proper eigenvalues and eigenvectors

In [14]:
#Matriz A dada por
A = Yt * Y 
#Valores y vectores propios de la matriz A
np.linalg.eig(A) 

(array([4.89832362e-02, 8.83773072e-09, 7.65501314e-03]),
 matrix([[-0.14970791, -0.82142745, -0.55031308],
         [-0.73822377,  0.46312144, -0.49045305],
         [-0.65773339, -0.33282949,  0.67573021]]))

In [16]:
#Se generan los autovalores
(Ut * A * U).round(5) 

array([[ 0.     ,  0.     , -0.     ],
       [-0.     ,  0.00766,  0.     ],
       [-0.     ,  0.     ,  0.04898]])

In [19]:
#Se generan los autovectores
v1 = np.array([[cos12 * cos13],  #Autovector 1
              [-sin12 * cos23 - cos12 * sin13 * sin23],
              [sin12 * sin23 - cos12 * sin13 * cos23]])

v2 = np.array([[sin12 * cos13],                         # Autovector 2
                [cos12 * cos23 - sin12 * sin13 * sin23], 
                [-cos12 * sin23 - sin12 * sin13 * cos23]])

v3 = np.array([[sin13],            # Autovector 3
                [cos13 * sin23], 
                [cos13 * cos23]])

#Estos coinciden con los autovectores de A
print("V1:{}".format(v1))
print("V2:{}".format(v2))
print("V3:{}".format(v3))

V1:[[ 0.82142745]
 [-0.46312144]
 [ 0.33282949]]
V2:[[ 0.55031308]
 [ 0.49045305]
 [-0.67573021]]
V3:[[0.14970791]
 [0.73822377]
 [0.65773339]]


In [20]:
#Autovalores de Y al cuadrado 
(np.linalg.eigvals(Y) ** 2), np.linalg.eigvals(A)


(array([1.31077419e-08+0.j        , 1.85544269e-03+0.01579159j,
        1.85544269e-03-0.01579159j]),
 array([4.89832362e-02, 8.83773072e-09, 7.65501314e-03]))

In [21]:
#Diferencia entre los dos valores propios(muy pequeña)
(np.linalg.eigvals(Y) ** 2)[1] - np.linalg.eigvals(A)[1] 


(0.0018554338528025314+0.015791591046463143j)

In [22]:
#Diferencia entre los dos valores propios(muy pequeña)
(np.linalg.eigvals(Y) ** 2)[2] - np.linalg.eigvals(A)[2] 


(-0.005799570451162216-0.015791591046463143j)